### ISSUE TITLE
widget: Item row titles overlap at smaller screen widths

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#1105]
![Screen Shot 2021-10-13 at 9 37 54 AM](https://user-images.githubusercontent.com/845363/137143803-2887b9b1-074e-41dd-b531-5423b77948e3.png)

**Comment by kelea99** [comment]
This looks fixed, @hackartisan (see below). No text overlap  for me and item jumps down  to new row. close ticket?

- Full size, laptop:
<img width="1372" alt="Full_laptop" src="https://user-images.githubusercontent.com/45043014/138230771-7586d18c-97e9-42de-b7d6-fd1b08ed29e7.png">

- Condensed  01:
<img width="732" alt="Med_test" src="https://user-images.githubusercontent.com/45043014/138230816-93846b85-f4c3-4c3e-9f1c-3a46f00cf32c.png">

- condensed  02  (Item  moves to new row  to make room):
<img width="635" alt="smallest_condenced" src="https://user-images.githubusercontent.com/45043014/138230967-cc7aeaf8-dbc7-4579-b0b0-629998538f0e.png">
