### ISSUE TITLE
Masonry view tooltip formatting is bad

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#1106]
![Screen Shot 2021-10-13 at 9 54 18 AM](https://user-images.githubusercontent.com/845363/137146981-55cccc12-af87-4ca3-bacc-6389bac15a3c.png)

Example: https://dpul-staging.princeton.edu/ga_treasures/catalog?page=4&q=&search_field=all_fields&view=masonry

There are several issues:

- [x] tooltip stacking behind other images
- [ ] Bookmark button is cut off (should remove?)
- [ ] General look and feel isn't good

**Comment by tpendragon** [comment]
Closing because nobody wants the masonry view anyways
