### ISSUE TITLE
Duplicate records in dpul

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/dpul#1120]
Not entirely sure that this is the cause of the error here, but there are duplicate records in DPUL:

https://dpul.princeton.edu/catalog/e046c1c558beb0f4c298637b0510cc4b
https://dpul.princeton.edu/catalog/6942fdc3-e0bd-491c-897d-50f7b804bbd2

[DPUL/production] ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "by_exhibit_and_doc"DETAIL:  Key (exhibit_id, document_type, document_id)=(97, SolrDocument, e046c1c558beb0f4c298637b0510cc4b) already exists.: INSERT INTO "spotlight_solr_document_sidecars" ("exhibit_id", "data", "created_at", "updated_at", "document_id", "document_type") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"

## Notes

It's normal for there to be two solr documents for the same record if it's in two different exhibits. We'll see if that's the case here or if it's a problem.

## Backtrace

    line 72 of [PROJECT_ROOT]/app/services/iiif_manifest.rb: add_metadata
    line 13 of [PROJECT_ROOT]/app/services/iiif_manifest.rb: to_solr
    line 69 of [PROJECT_ROOT]/app/models/iiif_resource.rb: reindex

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/81972204)

**Comment by hackartisan** [comment]
Pretty sure this was a resource that was in 2 different collections.
