### ISSUE TITLE
Save buttons are too tall

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#1162]
In the dashboard, for example. Here's a screenshot from the new collection form:

![Screen Shot 2021-10-20 at 4 50 47 PM](https://user-images.githubusercontent.com/845363/138170362-003888d4-312c-4971-a33d-b4e9ac6b4181.png)

**Comment by kelea99** [comment]
save button for saving searches are also too tall. Same height as mentioned above.
<img width="1440" alt="Screen Shot 2021-10-21 at 4 36 01 AM" src="https://user-images.githubusercontent.com/45043014/138241999-6243fb9f-1faa-444a-a90a-1aa786b26698.png">
