### ISSUE TITLE
Bookmarks page errors when you've saved bookmarks from cross-collection search

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1165]
I get an error when trying to go into my account to view my bookmarks. Not sure if the email functionality is there, but both of these things are needed for DPUL 3.0.

<img width="1440" alt="Screen Shot 2021-10-21 at 4 29 17 AM" src="https://user-images.githubusercontent.com/45043014/138241512-e549e086-4ac9-4326-b633-6db618e1d324.png">

<img width="1440" alt="Screen Shot 2021-10-21 at 4 29 04 AM" src="https://user-images.githubusercontent.com/45043014/138241534-61a8018d-a22a-4b4a-a5b3-ae191a829836.png">

**Comment by kelea99** [comment]
Im Still having errors with the bookmarks. This time it errors when trying to select bookmarks (collection: EAL):
![Screen Shot 2021-11-02 at 11 00 13 AM](https://user-images.githubusercontent.com/45043014/139873233-1bcdee4a-a4ac-4548-a42b-762223877af6.png)

**Comment by tpendragon** [comment]
We weren't able to reproduce together.
