### ISSUE TITLE
Blocks Release: Bulk edit options "add tags", "remove tags" not functioning and throwing up error.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1172]
This is a new 3.0 feature and there is no equiv. DPUL prod.
<img width="1440" alt="Screen Shot 2021-10-21 at 6 13 23 AM" src="https://user-images.githubusercontent.com/45043014/138258111-daab8a66-d416-4b96-bab1-ab8fda4f8744.png">
<img width="1440" alt="Screen Shot 2021-10-21 at 6 15 51 AM" src="https://user-images.githubusercontent.com/45043014/138258474-6d5a02ce-b0fc-4e87-a5d6-910dc6498271.png">
<img width="1440" alt="Screen Shot 2021-10-21 at 6 16 46 AM" src="https://user-images.githubusercontent.com/45043014/138258499-74128602-1530-4789-b092-45072835f354.png">

<img width="1440" alt="Screen Shot 2021-10-21 at 6 13 05 AM" src="https://user-images.githubusercontent.com/45043014/138258144-954cfba4-6b74-4e98-a8d2-f80b864f35db.png">

**Comment by tpendragon** [comment]
Honeybadger error: https://app.honeybadger.io/projects/51733/faults/82136845
