### ISSUE TITLE
QA test spotlight features new in 3.0

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1173]
checked boxes = functioning fine
- [x] Browse Group 
- [x] Bulk edit - add tags
- [x] Bulk edit - remove tags
- [x] Bulk edit - change visibility (see #1195)
- [x] Language bits (doh!) - (#972, #1122, #1154, #1136, #1169)

**Comment by hackartisan** [comment]
@kelea99 I believe the "language bits" are all taken care of? I added all the issues I could find but please let us know if there is something else.

**Comment by kelea99** [comment]
The only things I can see left for the Translations that still have issues are involving the search (dropdowns and faceting) and the metadata fields themselves):
1. Facet Fields
2. Field based Search
3. Sort fields within a search
4. metadata fields (I seem to remember this being a bigger request and not one for this workcycle). 
Otherwise everything looks functional! Playing around with the spanish language version of this one: https://dpul.princeton.edu/chilean_photographs?locale=es

**Comment by hackartisan** [comment]
@kelea99 okay I think the features have all been QA tested so I will close this issue. It would be helpful to have separate issues for any problems you're still seeing with language functionality. If you could give example pages with "I expected to see X but I saw Y" type descriptions that would be helpful.
