### ISSUE TITLE
Remove Blue boxes around selected items to filter

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1193]
When I click on a selection within a facet, blue boxes show up around the selected item before navigating to search results. I do not believe this is the intended function. Blue boxes are not present in DPUL prod.
![Blue-boxes_01](https://user-images.githubusercontent.com/45043014/139919941-386b949a-edcd-4543-9ce4-5988cf945207.png)

**Comment by kelea99** [comment]
Blue box appearance also happens when I click on Digital PUL  and the princeton university library logo in the header, exhibit tags on the home page (the tags highlight as light grey in prod), Actions (on right of homepage when logged in), around exhibit cards, etc. Is this a global fix?

**Comment by tpendragon** [comment]
Yeah, probably.

**Comment by tpendragon** [comment]
This only happens in firefox.

**Comment by tpendragon** [comment]
This is an accessibility feature.
