### ISSUE TITLE
alignment  for metadata in list view is not displaying consistently in all browsers.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1196]
Safari:
![Screen Shot 2021-11-02 at 4 12 47 PM](https://user-images.githubusercontent.com/45043014/139945601-58c68618-5fb8-4dcb-bf6d-7bc66c173fa2.png)

Firefox:
![Screen Shot 2021-11-02 at 4 17 07 PM](https://user-images.githubusercontent.com/45043014/139945693-058370fc-b8e3-422d-a42f-a29363f58bfa.png)

**Comment by sdellis** [comment]
@kelea99 I'm assuming we want it to look like it does in the Firefox screenshot in all browsers. Is this correct?

**Comment by kelea99** [comment]
Correct, @sdellis . It looks odd dropping below the thumbnail to me.  What are your thoughts?

**Comment by sdellis** [comment]
Yes, that's what I thought. I just wanted to double check!

**Comment by sdellis** [comment]
@kelea99 Actually, I do have one thought... if the title is more than one line to the title, it looks strange, even in Firefox, as the thumbnails seem to float. I suggest we line them up with the top of the title block, like we do in the catalog. 

We also may want to think about putting the thumbnails on the left if we know we are going to have thumbnails and they provide enough information to the user to help them decide relevance. See: https://www.nngroup.com/articles/mobile-list-thumbnail/

**Comment by hackartisan** [comment]
I think we have items without thumbnails. In the East Asian tables of contents collection: https://dpul.princeton.edu/ealtoc/catalog?utf8=%E2%9C%93&exhibit_id=ealtoc&search_field=all_fields&q=

**Comment by kelea99** [comment]
I would bet these are MVWs that did not have thumbnails selected for them in the parent, @hackartisan . checking EAL in figgy now and doing a test.

**Comment by kelea99** [comment]
yup.  Test was an MVW. no thumbnail set on the children or selected in the parent. I set one and now it shows in DPUL: https://dpul.princeton.edu/ealtoc/catalog?utf8=%E2%9C%93&exhibit_id=ealtoc&search_field=all_fields&q=Ce+fu+yuan+gui+%2F+%5BWang+Qinruo+deng+bian%5D.

**Comment by hackartisan** [comment]
Right, I think they don't have thumbnails on purpose. We might ask Tom.

**Comment by tpendragon** [comment]
Music content doesn't have thumbnails, either.

**Comment by kelea99** [comment]
l'll write to Tom about the EAL stuff now, @hackartisan .  @tpendragon can you give me an example of what you are seeing? Did a quick look at Valva, Music treasures, and Performance archive.  All but performance archive seem to have thumbnails, but I did not review the entirety.

**Comment by kelea99** [comment]
That is an interesting suggestion, @sdellis ! 

-  _I suggest we line them up with the top of the title block, like we do in the catalog._ I think I know what you are talking about but want to confirm. I think moving the thumbnail up toward the bookmark checkbox, like that of the online catalog makes sense.  From what I can see, it is the bookmark that is in alignment with the title, followed by the thumbnail beneath, with less padding in between. Is this correct? I really like the online catalog's alignment :)  thumbnails below:
- Orangelight
![Screen Shot 2021-11-05 at 11 03 37 AM](https://user-images.githubusercontent.com/45043014/140532773-77f2239b-00ec-48fa-a47b-2f472d555687.png)

- DPUL
![Screen Shot 2021-11-05 at 11 02 35 AM](https://user-images.githubusercontent.com/45043014/140532832-0b0e106d-3ab9-4654-86ee-7ab14eeb59d8.png)

**Comment by kelea99** [comment]
Reasoning for high priority to be done this work cycle: It should be consistent across platforms and as a list view it should be visually intuitive.  Especially considering the Milberg exhibitions and other exhibits also built in DPUL utiize the list view for items and an overview of the most important metadata/links to searches/etc...

**Comment by sdellis** [comment]
The simplest solution to this misalignment would be to move the thumbnail inside of the column to the right of the title, below the bookmark checkbox. However, the use of ViewComponents seems to create some obstacles since the element classes are defined in ruby classes. Due to the actions loop and coupled wrapper defined in the method, it's not as simple as placing the "thumbnails" component into a layout.  

However, OrangeLight developers seem to have been able to position the thumbnail without overriding any ViewComponents (I would expect a "components" folder here): https://github.com/pulibrary/orangelight/tree/main/app 

Not quite sure how to move the thumbnail into the bookmark `<div>`.

**Comment by hackartisan** [comment]
Orangelight does it here in a view override for the index item partial https://github.com/pulibrary/orangelight/blob/ace3e1ba6188b85a091eac310adb82b18ac1cfe2/app/views/catalog/_index_default.html.erb

Doing this with an override that doesn't use viewcomponents would be an option.
