### ISSUE TITLE
Titles are not displaying as expected for entirety of items in Performance Archive Audio Collection+Sub-collections

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1202]
[DPUL LINK](https://dpul.princeton.edu/performances/catalog?q=&search_field=all_fields)

Sample looked at in Figgy and Orangelight. Titles display fine in both applications for Performance Archive Audio Collection/Subcollections

**Comment by hackartisan** [comment]
full_title_tesim isn't getting indexed.

**Comment by hackartisan** [comment]
one option is to set 
https://github.com/pulibrary/dpul/blob/b569884856e9470d5318033dbd4944e8415cd2a9/config/initializers/spotlight_config.rb#L8

to `readonly_title_tesim`

But also why isn't that value getting indexed?

**Comment by eliotjordan** [comment]
🐢 🐢 🐢 

Bottom of the hole is the iiif-prezi gem. Our code is calling `manifest.label` and it is returning nil. `label` is where the value of `full_title_tesim` originates.

https://github.com/iiif-prezi/osullivan/blob/development/lib/iiif/presentation/manifest.rb#L5
