### ISSUE TITLE
Manifest for exhibit 64 times out on reindex

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#1203]
## Backtrace

    line 5 of [PROJECT_ROOT]/app/models/external_manifest.rb: load
    line 10 of [PROJECT_ROOT]/app/models/collection_manifest.rb: find_by_slug
    line 19 of [PROJECT_ROOT]/app/models/exhibit_proxy.rb: collection_manifest

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/81453505)

**Comment by eliotjordan** [comment]
This is collection: https://figgy.princeton.edu/catalog/e9709523-ec23-4eb0-9dd3-002746b91d13

There are ~ 15000 items in the collection and the manifest takes 15 seconds to load.

We need to increase the timeout value here:
https://github.com/pulibrary/dpul/blob/d7b18fbeccded55474727243282118ba4189d49e/app/models/external_manifest.rb#L5
