### ISSUE TITLE
Error when removing items from solr

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#1204]
[DPUL/production] Blacklight::Exceptions::InvalidRequest: RSolr::Error::InvalidRubyResponse - 200 OKError: HTTP/1.1 200 OKServer: nginx/1.21.3Date: Tue, 02 Nov 2

## Backtrace

    line 9 of [PROJECT_ROOT]/app/repositories/friendly_id_repository.rb: find
    line 19 of [PROJECT_ROOT]/app/models/solr_document.rb: find
    line 73 of [PROJECT_ROOT]/app/models/iiif_resource.rb: remove_from_solr

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/80042891)

**Comment by eliotjordan** [comment]
Closing because this might be an issue with the network and not with DPUL. Re-open if it becomes a problem.
