### ISSUE TITLE
[DPUL/production] NoMethodError: undefined method `manifests' for nil:NilClass

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#1205]
We aren't getting the following collections:

```
irb(main):009:0> Spotlight::Exhibit.find(63)
=> #<Spotlight::Exhibit id: 63, title: "Latin American, Caribbean, and Spanish Collections", subtitle: nil, slug: "LAECS", description: nil, created_at: "2020-06-18 14:10:36", updated_at: "2021-10-08 16:14:20", layout: nil, published: false, published_at: nil, featured_image: nil, masthead_id: nil, thumbnail_id: nil, weight: 42, site_id: 1, theme: nil, thumbnails_enabled: true, condensed_viewer: false, tag_list: nil>
irb(main):010:0> Spotlight::Exhibit.find(88)
=> #<Spotlight::Exhibit id: 88, title: "Charles Rogers Collection", subtitle: nil, slug: "Rogers", description: nil, created_at: "2021-02-16 15:37:50", updated_at: "2021-10-21 08:08:32", layout: nil, published: false, published_at: nil, featured_image: nil, masthead_id: nil, thumbnail_id: nil, weight: 66, site_id: 1, theme: nil, thumbnails_enabled: true, condensed_viewer: false, tag_list: nil>
irb(main):011:0> Spotlight::Exhibit.find(93)
=> #<Spotlight::Exhibit id: 93, title: "Historical Photograph Collection, Grounds and Buil...", subtitle: nil, slug: "AC111", description: nil, created_at: "2021-03-16 17:06:24", updated_at: "2021-10-21 08:08:31", layout: nil, published: false, published_at: nil, featured_image: nil, masthead_id: nil, thumbnail_id: nil, weight: 61, site_id: 1, theme: nil, thumbnails_enabled: true, condensed_viewer: false, tag_list: nil>
```

## Backtrace

    line 32 of [PROJECT_ROOT]/app/models/exhibit_proxy.rb: members
    line 19 of [PROJECT_ROOT]/app/models/exhibit_proxy.rb: estimated_size
    line 22 of [PROJECT_ROOT]/app/jobs/spotlight/reindex_job.rb: block in <class:ReindexJob>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/82380662)

**Comment by hackartisan** [comment]
These correspond to the following dpul collections:

- https://dpul-staging.princeton.edu/LAECS
- https://dpul-staging.princeton.edu/AC111
- https://dpul-staging.princeton.edu/Rogers

It seems like they may be old test collections or something? @kelea99 are these still in development? If not could we delete them? And if so we should update their slugs to point correctly to figgy collections.

**Comment by kelea99** [comment]
All of these were DPUL exhibits that were never built or whose collecitons changed. Deleting. 
Deleted in DPUL prod: 
- [ ]     https://dpul-staging.princeton.edu/LAECS
- [ ]     https://dpul-staging.princeton.edu/AC111
- [ ]     https://dpul-staging.princeton.edu/Rogers

**Comment by hackartisan** [comment]
Thanks; I deleted the jobs, too.
