### ISSUE TITLE
Map box number information from Ephemera Projects items to DPUL exhibits containing ephemera project items

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1213]
I have a feeling this is also a figgy ticket.  Fernando would  like to show box and folder number information in DPUL exhibits for his ephemera. We have the folder number displaying fine, but the Box number is not mapped.  

Spain 15M example from DPUL,[ item level](https://dpul.princeton.edu/15m/catalog/f092c02a-9d59-4c5d-9158-e0dceb92e57f)
Spain 15M example from Figgy, [item level](https://figgy.princeton.edu/catalog/f092c02a-9d59-4c5d-9158-e0dceb92e57f)
Collection example (DPUL): https://dpul.princeton.edu/15m
Project example (Figgy): https://figgy.princeton.edu/catalog/70433c80-ca9e-4ade-9687-8c98f72875bc

**Comment by hackartisan** [comment]
@kelea99 should this be a separate "box number" field like the "folder number" one or should it all be together with some other heading, e.g. "Physical location: Box X, Folder Y"?

findingaids appears to have "located in" and "storage note" see for example https://findingaids.princeton.edu/catalog/RBD1-1_c4886

**Comment by hackartisan** [comment]
This one has a field called "location" https://dpul.princeton.edu/pudl0036/catalog/b5644w35k

**Comment by kelea99** [comment]
@hackartisan, good questtion. I believe Ideally reflect the field in the  LAE site,  like your idea of "physical location: Box X: Folder Y" 
[Example here](https://lae.princeton.edu/catalog/49d2544f-ec0d-490d-b868-535a1cbc8601?locale=en#?c=0&m=0&s=0&cv=0&xywh=-1316%2C-272%2C6004%2C5427)
Entry format from example above:
Container:   Box 20, Folder 107

**Comment by kelea99** [comment]
@hackartisan checking in on this one, as I have to reply to Fernando for something else today and can give him an update.

**Comment by kelea99** [comment]
Closing  and adding comment referencing  this ticket in https://github.com/pulibrary/dpul/issues/1275 and https://github.com/pulibrary/figgy/issues/4832
