### ISSUE TITLE
Reindexing status error occurred when manually reindexing Shakespeare and Co. exhibit.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1230]
Not sure what to do here. The numbers of items that were originally queued up for reindex is incorrect 3960 noted in Reindex; 803 total in collection - see [figgy ](https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Shakespeare+and+Company&f%5Bstate_ssim%5D%5B%5D=complete), and the reindex errors within seconds (schreenshot below): 
![Screen Shot 2021-11-09 at 2 30 15 PM](https://user-images.githubusercontent.com/45043014/140992065-dbefa486-bdf6-4853-aa36-3c7224492872.png)

**Comment by kelea99** [comment]
Fascinating update. The number of items to be reindexed is rising (I have attempted a second re-index. its just kinda doing its thing on its own), and the numbers of items in the exhibit are growing (see the numbers).  
![Screen Shot 2021-11-09 at 3 04 22 PM](https://user-images.githubusercontent.com/45043014/140996706-0d4e2fca-0426-4fa2-a16d-1e3c382d2cee.png)

**Comment by hackartisan** [comment]
@kelea99 the reindexing widget is pretty much completely broken. I added a little bit more to  https://github.com/pulibrary/dpul/issues/1094 and will close this one as a duplicate.

**Comment by kelea99** [comment]
doh! forgot about that ticket! sounds great. fwiw, it did end up getting all the right items into the collection, even though the error popped up and the numbers in the pop up are totes wrong.
