### ISSUE TITLE
Image upload for thumbnail in browse category is broken

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1232]
I  uploaded a jpeg image via the item upload option for thumbnail in my newly created browse category.
1. I selected the area I wished to display via the box. works fine.
2. Clicked save.
3. Image broken icon displays on the browse category lists in the dashboard. 
4. Browse category is not the same shape or size as the others on the browse page
![Screen Shot 2021-11-10 at 8 58 53 AM](https://user-images.githubusercontent.com/45043014/141126689-1d049559-68c6-44a1-8a33-b97323079980.png)
![Screen Shot 2021-11-10 at 8 59 04 AM](https://user-images.githubusercontent.com/45043014/141126764-9cc5ec28-4a23-4980-92e6-d779864161ea.png)
![Screen Shot 2021-11-10 at 8 59 11 AM](https://user-images.githubusercontent.com/45043014/141126783-cf2236a7-d0ea-48a8-b402-718e70219470.png)

**Comment by kelea99** [comment]
Image selection from the source is functional.  I can select a title from the pulldown, which does come up.  It saves. It displays in the dashboard as well as the browse page.

**Comment by hackartisan** [comment]
This has been working recently.
