### ISSUE TITLE
Index date_created to sort date if there's no `date` field

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1240]
This collection has `date_created` values but no `date` values, and they want to be able to sort by date: https://dpul.princeton.edu/shakespeareandco/browse/logbooks-c962b498-bac0-40eb-a223-c206b7f04f63

pull from the date_created if there's no date when populating the sort date field.

**Comment by hackartisan** [comment]
It looks like the sort date comes from the `date` field, which these items maybe don't have. They seem to have a `date_created` value instead.
