### ISSUE TITLE
All items with "Inventories, Order Records Clients" title are not displaying in title dropdown for Widgets

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1243]
The same title for multiple items is used: "Inventories, Order Records, Clients". I am not sure if the issue is that there is a maximum number (twenty??)  given for title dropdown amount allowed?  

Total number (figgy) is 45: https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Shakespeare+and+Company&f%5Bstate_ssim%5D%5B%5D=complete&f%5Bvisibility_ssim%5D%5B%5D=open&q=%22Inventories%2C+order+records%2C+clients%22

Total dropdown number is 20 from what i can see and selection changes depending on the search entry for the full title, "inv", "inve", "Invent"...ettc..., "Inventories"
![Screen Shot 2021-11-11 at 4 47 36 PM](https://user-images.githubusercontent.com/45043014/141373967-f63f0f5d-0a45-4414-b22b-3e798cf33c40.png)

**Comment by kelea99** [comment]
Read through #1157 and #1159 just to make sure I'm not missing something. Tested dropdown  selections for other collections (Dissidents, Piranesi, Western Americana,  Chilean, badakhshan) and it was either more than 20 (will count), 20, or 10.

**Comment by tpendragon** [comment]
We can solve this by making override title work as a search term for this widget.

**Comment by hackartisan** [comment]
This doesn't work still but we don't need it to anymore because we got the feature implemented in a preferred way (with date sorting).
