### ISSUE TITLE
Indexing/reindexing for items in DPUL is returning fewer items than what is in the collection and should be displaying in DPUL

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1267]
Thomas wrote about the numbers in his [Soviet era childrens books collection](https://dpul.princeton.edu/slavic) diminishing, not growing, within the  DPUL Slavic collections. He was (at the time) at 231 items in figgy and DPUL and he was then at 212.  What i did:
1. checked numbers in DPUL versus figgy
2. Reindexed items in DPUL 

Results: numbers for all collections diminished to 42.  Reindexing stated 42 items were being reindexed (versus over 1,000). 

past occurrences?:  Issues for reindexing DPUL collections post-upgrade have happened. 

Figgy Collection: https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Soviet+Era+Books+for+Children+and+Youth

## DIagnosis

ExhibitReindexJob starts, gets through the first 42 resources which are public, hits the 43rd item which is private and new, and tries to create it. It "saves", but doesn't throw an exception because it's not save!, and then tries to queue a job - but that new resource has no ID, because it failed validation, because it's a private URL. So the job errors, and only the first 42 get processed for indexing.

**Comment by kelea99** [comment]
impact of issue: the DPUL collection is the only space for items to be viewed as a collection and stakeholder was going to be showing off the DPUL site within the next several days for consultations and presentations. So, while not ASAP, it is a high priority.

**Comment by tpendragon** [comment]
Current theory is that things that need new resources aren't being created because of some validation error. Trying out reindexing new resources with `save!` vs `save` in reindex exhibit job to get some better validation errors.

**Comment by kelea99** [comment]
Should Items marked as private not have collection tags for collections that are pushed to DPUL? is that what is erroring, @tpendragon ?

**Comment by tpendragon** [comment]
It's fine, @kelea99. I think we have it fixed - reindexing now.

**Comment by kelea99** [comment]
just a heads up @tpendragon  that ellen just reported the same thing.  is the reindex for all collections or just Thomas's? other affected collection: SAE (unpublished): https://dpul.princeton.edu/sae

**Comment by tpendragon** [comment]
@kelea99 I hit the reindex button for that. It should happen after the slavic one is done.

**Comment by kelea99** [comment]
post fix, I can hit a reindex on any i know to have private items, if it helps. thank you!

**Comment by hackartisan** [comment]
related honeybadger errors:
* https://app.honeybadger.io/projects/51733/faults/82603381
* https://app.honeybadger.io/projects/51733/faults/82773830
