### ISSUE TITLE
Map figgy local identifier for legacy finding aids items  to DPUL

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1269]
User request:  We need to have the component ids in the metadata for each item in Post Cards (a legacy collection from PUDL migration). Items were ingested at the item level along with all item level metadata ( this stuff is not linked to the source metadata in FA). The local identifier shows the component information needed in the DPUL site.  

Figgy collection: https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Postcards+-+Item+level+ingest

DPUL collection (unpublished): https://dpul.princeton.edu/historical-postcards

**Comment by hackartisan** [comment]
These were reingested and it works now
