### ISSUE TITLE
RTL Titles in search results cause "and" to look like it's prefixed before everything.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul#1273]
See https://dpul.princeton.edu/islamicmss/catalog?utf8=%E2%9C%93&exhibit_id=islamicmss&search_field=all_fields&q=Hida%CC%84yat+al-d%CC%A3a%CC%84lli%CC%84n+wa-kifa%CC%84yat+al-mu%CA%BEmini%CC%84n

The text is "كتاب هداية الضالين وكفاية المؤمنين / از فاضل جديد الاسلم عليقلي. and Kitāb-i Hidāyat al-ḍāllīn wa-kifāyat al-muʾminīn / az fāḍil Jadīd al-Islam ʻAlī-Qulī.", but since it's tagged RTL it renders the "and" first.

**Comment by tpendragon** [comment]
PO has marked this as "ticket to improve User's lives."

**Comment by kelea99** [comment]
I think that would work and would match the format on item level view in DPUL and in the online catalog 
![Screen Shot 2022-01-04 at 10 48 28 AM (2)](https://user-images.githubusercontent.com/45043014/148085626-73da9b96-cecb-4319-8abe-1e2e253e9d38.png)
![Screen Shot 2022-01-04 at 10 48 22 AM (2)](https://user-images.githubusercontent.com/45043014/148085653-ce5453fb-6b6d-4797-9e7b-a237ee94866f.png)


VERSUS the "and" in list view:
![Screen Shot 2022-01-04 at 10 49 41 AM (2)](https://user-images.githubusercontent.com/45043014/148085738-bc29468c-b03a-4244-92ca-db88ea3de950.png)
