### ISSUE TITLE
Fields missing from json search results needed for bento search

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#1277]
Currently no results are showing for dpul in the [bento search](https://library.princeton.edu/find/all/art). Probably this broke with the blacklight upgrade.

Here is some client code showing previous expected behavior, with attempts to find data in the new format: https://github.com/pulibrary/discoveryutils/pull/201/files#diff-69331d0313a44ff9b652e6ee7f61c7d05c3588ea17d8b44afd02d064b4d63fecR26-R42

However, some of the required fields are not published at all. Currently it looks like only collection and creator are coming through: https://dpul.princeton.edu/catalog.json?utf8=%E2%9C%93&search_field=all_fields&q=music

We at least need title and url.

## Sudden Priority Justification

Bento search is a primary means of accessing our content and our colleagues have put in time to try to fix this on their side.

We can wait until the second week of this cycle to tackle this, in an effort to minimize the impact of being pulled away.

**Comment by tpendragon** [comment]
Our bento search is a primary means of folks finding our content. I'm going to mark this a sudden priority, but recommend we don't tackle it until next week.
