### ISSUE TITLE
More/Less link actions in contents listing are reversed.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1280]
The more/less hyperlink does the opposite of what is says when clicked: https://dpul.princeton.edu/discrimination_employment_pamphlets/catalog/dc0z709627k

![Screen Shot 2022-01-12 at 8 38 50 AM (2)](https://user-images.githubusercontent.com/45043014/149150875-4dd92f76-c087-4e22-9823-df9dc7b16676.png)
![Screen Shot 2022-01-12 at 8 37 41 AM (2)](https://user-images.githubusercontent.com/45043014/149150900-57833933-1424-4135-ae7e-06047ddff498.png)

**Comment by tpendragon** [comment]
@joycebcat just noticed this again.

**Comment by tpendragon** [comment]
Closed by #1357
