### ISSUE TITLE
Item Carousel Widget is broken for MVWs

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1287]
### Summary
Elements within the Item Embed carousel widget are not functioning at all or not behaving in the expected ways.
### Impact
DPUL builder currently working on a forthcoming exhibit is unable to use the widget that was to be on the homepage of their exhibit. several DPUL exhibits use this same format, implementing item carousel on homepages (i.e. the first page a visitor sees).
### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will priotize

### Expected behaviour
- Add Item within widget from dropdown
- Item comes up with thumbnail to left and pages at bottom to change/chose from for carousel.
- Item may be removed by clicking "remove" to the right of the bar containing the selected item within the widget
- Item is crisp and may be viewed clearly by users in item carousel in front end
### Actual behaviour
- Add Item within widget from dropdown
- Item comes up but not always with thumbnail to left and not always with pages at bottom to change/chose from for carousel (I believe the MVW in this instance is making making the widget die a slow death).
- Item may not be removed by clicking "remove" to the right of the bar containing selected item within the widget and in many instances DPUL becomes unresponsive
- Item is blurry and illegible in item carousel in front end
### Steps to reproduce behaviour
1. Go to https://dpul.princeton.edu/happy_gall-entines_day
2. Enter edit mode
3. Select "Item Carousel" Widget
4. Start Adding items from the drop down - The red volume (the MVW) will freeze the system immediately. If you exclude it from the options, the item behaves as expected until you try to remove the item from the carousel list and when you view the fuzzy result in the front end after you save).
### Screenshots
![Screen Shot 2022-01-20 at 2 43 21 PM (2)](https://user-images.githubusercontent.com/45043014/150411367-d29e1bc4-ea92-4bd4-8824-ca2d90a62e06.png)
![Screen Shot 2022-01-20 at 2 48 01 PM (2)](https://user-images.githubusercontent.com/45043014/150411469-6c06a71e-9d51-4b40-ae8e-ad101a021d3c.png)

## Sudden Priority Justification

The carousel is a primary showpiece of a number of our collections. Exhibit creators can't make new exhibits the way they'd like to without it. In this particular case they'd like the exhibit live by valentine's day.

**Comment by kelea99** [comment]
Just checking in on this on, @tpendragon .

**Comment by tpendragon** [comment]
It's prioritized for the maintenance cycle this week.

**Comment by tpendragon** [comment]
Example of a collection that has a working one (from before bug): https://dpul.princeton.edu/gnib

**Comment by kelea99** [comment]
hi, @hackartisan ! Same thing happening again, I think. Im reopening this ticket, but Im happy to make a new one. Natalie and Fernando are having the same problem on the home page of:
https://dpul.princeton.edu/lae-dig-microfilm

**Comment by kelea99** [comment]
hard deadline: this has to be ready for a conference fernando is attending in June of this year.

**Comment by hackartisan** [comment]
full_image_url_ssm is configured for the autocomplete json response, but is not included in the field list for the query sent to solr:

`"fl"=>"id full_title_tesim thumbnail_ssim content_metadata_iiif_manifest_field_ssi",`

**Comment by hackartisan** [comment]
We found that non-MVWs have a value for iiif_tilesource once they're saved by trevor, but MVWs do not. This makes https://github.com/projectblacklight/spotlight/blob/main/app/views/spotlight/sir_trevor/blocks/_solr_documents_carousel_block.html.erb#L13 work for non-mvws, and a larger image is displayed. Note that neither is getting the full_image_url value.

That all happens in https://github.com/projectblacklight/spotlight/blob/main/app/javascript/spotlight/admin/iiif.js

But it seems too hard to make that work for MVWs. We're already doing it on the ruby side, so let's use what we already have.

Plan:

1. write a test on the autocomplete endpoint to ensure it returns a full_image_url. Maybe add something around https://github.com/pulibrary/dpul/blob/403a9311d1ec21d1544588fcc5ad1e4ed5c8fa4e/spec/features/catalog_spec.rb#L66
1. Make autocomplete return full_image_url_ssm by setting the field list in the initializer. Add a `fl` to the setting as seen in https://github.com/projectblacklight/spotlight/blob/a29b6bd3dc1e97fcc8f49a0273c90516af4d3f49/lib/generators/spotlight/templates/config/initializers/spotlight_initializer.rb#L32
1. Index the full image url at a slightly larger size. see https://github.com/pulibrary/dpul/blob/403a9311d1ec21d1544588fcc5ad1e4ed5c8fa4e/app/services/iiif_manifest.rb#L43-L47
