### ISSUE TITLE
"Title Override" Field is broken

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1297]
### Summary
I added a title override as an example in an [unpublished DPUL exhibit ](https://dpul.princeton.edu/coins_geniza)for student interested in building a DPUL exhibit. I added the title override, saved, and the title of the item did not change.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This will impact any and all online components to physical exhibits, including Milberg Gallery online components. This will impact any exhibits utilizing title overrides for their content, like Shakespeare and Co. 

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked_
This field's functionality is mandatory for the forthcoming Alchemy exhibit, to open in April. 
### Expected behaviour
When i go to edit an item in my exhibit, I expect to add the title override, click save, and have my new title replace the title being pushed from Figgy.
### Actual behaviour
When i go to edit an item in my exhibit, I add the title override, click save and the title pushed from figgy is still there. My added title in Title Override is nowhere to be seen in the front facing page. But it still exists in edit mode.

### Steps to reproduce behaviour
Go to[ this item](https://dpul.princeton.edu/coins_geniza/catalog/dc1n79hf550)  in DPUL
Click on edit
See the title override field/add new title override
Save

### Screenshots
![Screen Shot 2022-02-04 at 2 20 01 PM (2)](https://user-images.githubusercontent.com/45043014/152590047-d8e73f30-8b3b-4b5b-afc3-cb9ba31227a9.png)
![Screen Shot 2022-02-04 at 2 20 06 PM (2)](https://user-images.githubusercontent.com/45043014/152590081-85d2ec94-72a9-483d-b62b-30a238ab942d.png)

**Comment by tpendragon** [comment]
We found that when going to a show page for a record which is in two different exhibits, the solr record that's being rendered might not be the correct one.

For example, https://dpul.princeton.edu/happy_gall-entines_day/catalog/nz8060449 should come from the happy_gall-entines_day exhibit, but it's the one from PUDL0017 (you can tell by going to `/raw` and looking at the exhibit prefix..

**Comment by kelea99** [comment]
Is the solr record that is rendered dictated by what DPUL collection was created first with that item (like your example link)? or is it random? we have items with multiple collection tags in figgy. I wonder what the consequences are?

**Comment by hackartisan** [comment]
A solr record is generated for each unique collection / resource pair. We need to fix the code to pull the right record.
