### ISSUE TITLE
SOLR not indexing 856 in DPUL and links are not visible in item level metadata

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1307]
### Summary
Discovered in Performance Archive materials. Links that have been provided within MARC record 856 fields that connect to concert programs for the sound recording are not visible within the item level metadata in DPUL.  

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
While this is not hindering work, it would solve an issue we are having with needing to connect Audio files to scanned resources in some way.   

### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [x] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_

### Expected behaviour
When I go to [an item ](https://dpul.princeton.edu/performances/catalog/e8e51703-43e9-48c7-bb31-a0700526a8f0) in the performance archive, I expect to see a [link]( https://library.princeton.edu/music/programs/2020-03-06-07_PUO.pdf ) to the Concert Program, which is available via the 856 in the Marc (see [catalog record](https://catalog.princeton.edu/catalog/99118896433506421/staff_view))

### Actual behaviour
When I go to [an item ](https://dpul.princeton.edu/performances/catalog/e8e51703-43e9-48c7-bb31-a0700526a8f0) in the performance archive,  I do not see any link to the Concert Program.  The description mentions that a complete program is available online, but in a different field (this is a 500 field).

### Steps to reproduce behaviour
Go to the DPUL Performance archive https://dpul.princeton.edu/performances/catalog/e8e51703-43e9-48c7-bb31-a0700526a8f0
confirm in OL record that there is an 856. 
look to see if any link is represented within DPUL for that item.

**Comment by hackartisan** [comment]
Usually the 856es have arks, which would often just link back to DPUL.

**Comment by hackartisan** [comment]
Close in favor of pulibrary/figgy#5076
