### ISSUE TITLE
Pages Widget is not  producing drop down options or allowing manually typed page additions  in edit mode of  of a DPUL home page.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1313]
### Summary
I created a skeleton DPUL site for a site builder, so that they would get a better idea what was possible in DPUL for their content.  I added the pages widget for the home page, and I created 2 test feature pages for them to work with.  I am able to add pages to the widget with no problems. I have tried in both firefox and chrome.  The site builder could not add pages in the Pages widget, but could move/delete/etc.. the pages that I added in edit mode and select images for the thumbnails for those pages.  He tried on Microsoft machines and his mac. He tried in Firefox and Chrome. Same problem. We both have admin access to his site.  Potentially totes wrong ideas:

- Since I created the feature and about pages, he was not able to add them to the widget for reasons I do not understand. 
- Since I added the  pages widget to the home page, he was not able to add anything to that widget for reasons I do not understand.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
We were able to troubleshoot this by having me add all the pages he wanted on his home page, but this route is not sustainable if we intend on folks building their own DPUL sites and if we have multiple people working on one site together.

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_
Emma will be building her first DPUL site for a milberg exhibit, due to launch April 1-6.  We should make sure things are functioning  so that work within this widget can be done by anyone. This widget is used every time for milberg.

### Expected behaviour
Regardless of who creates a page or adds a widget to a page within a DPUL site, any site builder assigned to that DPUL exhibit will be able to add pages from a dropdown of options to the Pages Widget in edit mode.

### Actual behaviour
Not all site builders are able to add pages to the Pages widget in DPUL. When the site builder goes to the home page, clicked on edit, and tries to add a page to the pages widget, he gets zero drop down options and nothing links up when he types the page title in manually.

### Steps to reproduce behaviour

- Go to: https://dpul.princeton.edu/john-lewis-and-selma
- Go to Edit in the home page
- click within "Enter a title" box, on the last widget option at the bottom of the page.
- I see a drop down or options when i start typing a title. What do you see?

### Screenshots
![Screen Shot 2022-02-15 at 11 53 20 AM (2)](https://user-images.githubusercontent.com/45043014/154109841-61271e70-7f07-4ed1-9477-5488da5724fd.png)

What one should see when you start typing:
![Screen Shot 2022-02-15 at 11 54 36 AM (2)](https://user-images.githubusercontent.com/45043014/154110005-4be27797-e534-4cab-ad86-6b665b678840.png)

**Comment by tpendragon** [comment]
We'll prioritize this for the maintenance week on March 21.

**Comment by kelea99** [comment]
Also see #1321 . Maybe related?
