### ISSUE TITLE
Feature Pages reorganization will not hold save for Admins other than PO

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1321]
### Summary
Reported by Emma Sarconi and tested by Emma and Kim together. When Emma rearranges the feature pages, saves and then resaves the page, all pages go back to a previous organization (not always the same). The pages to not reorder themselves by alphabet or consistently. I reordered the pages for her, clicked save, and it has held. 

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [x] asap - week of March 21? Might be similar issue as #1313?
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_
This is hindering, but not halting, work on the forthcoming Alchemy online companion to a Milberg Gallery Exhibition
### Expected behaviour
When anyone who is a curator or admin reorders and saves a new organization of pages in Dashboard, I expect that new organization to be saved. 

### Actual behaviour
When I reorder and save a new organization of feature pages in Dashboard, I see the new saved organization.
When Emma reorders and saves the new organization of feature pages in Dashboard, the new organization does not remain saved.

### Steps to reproduce behaviour
1. Go to dashboard in Alchemy:https://dpul.princeton.edu/alchemy/feature
2. re order pages in feature pages
3. what happens if you have my permissions? what happens when you have standard Admin permissions? I am the owner, i would assume.

**Comment by tpendragon** [comment]
Emma says it's working.
