### ISSUE TITLE
Error message appeared in reindexing status for Slavic Collections in Dashboard

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1340]
### Summary
The item numbers were off (not all items were in his exhibition that should be)for Thomas Keenan's Slavic Collections DPUL exhibit. I ran a reindex for the site and it is still re-populating. however, an error message is currently in the reindexing status (but the numbers are still growing, so the reindex is still happening). As long as the reindex works,  Thomas will have what he needs by deadline. But we should probably look into why a manual reindex was needed  and why an error message appeared  in the reindexing status. 

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
If the reindex works, Thomas will have what he needs. But we should check again before his deadline day.

### Priority recommendation

- [ ] asap *Only if reindex does not work*
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_
ASAP to meet deadline for thomas, but only if the reindex does not work.
### Expected behaviour
I expect all open items from Figgy Collections to available in their DPUL sites. If I have to manually reindex the site, I expect  The reindex to  occur without an  error message

### Actual behaviour
All open items from Figgy Collections were not available in Thomas's DPUL site.  I manually reindexed the site and it threw an error message in the reindexing status within the dashboard. However, the numbers being reindexed continue to grow, inferring the reindex is still happening.

### Steps to reproduce behaviour
1. Go to dasboard
2. go to Items
3. Select reindex
4. wait

### Screenshots
<img width="1440" alt="Screen Shot 2022-04-14 at 8 38 09 PM" src="https://user-images.githubusercontent.com/45043014/163499887-62ace02c-9702-4cab-8a7e-718f9d7fbb1a.png">

**Comment by hackartisan** [comment]
The reindex got all the items in.

**Comment by hackartisan** [comment]
I found the error! If you go to the dashboard, in the list of "recent item indexing activity" click on "failed" and you'll get a modal with some formatting problems.

It looks like these errors get captured here instead of sending to honeybadger, and they also keep the jobs from retrying? Seems potentially related to #1294

**Comment by hackartisan** [comment]
Here's an example one (they all look pretty much like this):

```
undefined method `[]' for nil:NilClass

{
  "backtrace": "/opt/dpul/releases/20220328195027/app/services/iiif_manifest.rb:74:in `noid'\n/opt/dpul/releases/20220328195027/app/services/iiif_manifest.rb:18:in `add_noid'\n/opt/dpul/releases/20220328195027/app/services/iiif_manifest.rb:6:in `to_solr'\n/opt/dpul/shared/bundle/ruby/2.7.0/gems/blacklight-spotlight-3.0.3/app/models/spotlight/resources/iiif_harvester.rb:23:in `block (2 levels) in indexing_pipeline'\n/opt/dpul/shared/bundle/ruby/2.7.0/gems/blacklight-spotlight-3.0.3/app/services/spotlight/etl/step.rb:24:in `block (2 levels) in call'",
  "resource_id": null
}
```

**Comment by hackartisan** [comment]
Most of these are this same "Undefined method [] for nil" error. Some are timeouts and other things like that. Some example figgy urls for the nil error:

https://figgy.princeton.edu/concern/scanned_resources/8eeef309-a2c1-4297-aef5-c22c92e05b7f/manifest https://figgy.princeton.edu/concern/scanned_resources/d3e252e1-0918-4d1f-bb28-b89e92457981/manifest https://figgy.princeton.edu/concern/scanned_resources/823df728-9826-44ae-8e96-35fecb15d55c/manifest
https://figgy.princeton.edu/concern/scanned_resources/7bb24f4c-3501-446d-9bbe-f37e71a4a4df/manifest https://figgy.princeton.edu/concern/scanned_resources/8ceabd44-ba47-4b42-bd65-1e95f9d190bf/manifest

**Comment by hackartisan** [comment]
A reindex on staging went through with no errors. There were errors on prod. Staging doesn't seem to index campus-only materials, while prod does. Maybe there's a problem with those resources.

**Comment by hackartisan** [comment]
here is the resource that is erroring: https://figgy.princeton.edu/catalog/d2d488af-2980-4554-a9ef-aacbaf463ec8

**Comment by kelea99** [comment]
I know there was a bug with DPUL prod and a visibility setting that @tpendragon checked for me. I think there is a ticket.  Looking

**Comment by kelea99** [comment]
Ha! https://github.com/pulibrary/dpul/issues/1300

**Comment by hackartisan** [comment]
@kelea99 thank you!! It seems likely that is indeed the same issue.
