### ISSUE TITLE
Load time for home page of Sid Lapidus DPUL Exhibit is Super Slow.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1360]
### Summary
The Sid Lapidus DPUL exhibit is taking a long time to load when you navigate to the home page.  [Data Dog Link] ([https://app.datadoghq.com/apm/resource/pomegranate/rack.request/892147145d819509?quer[…]ts%3Acount&start=1657287118214&end=1657290718214&paused=true](https://app.datadoghq.com/apm/resource/pomegranate/rack.request/892147145d819509?query=resource_name%3A%22Spotlight%3A%3AHomePagesController%23show%22%20operation_name%3Arack.request%20service%3Apomegranate%20env%3Anone%20%40http.path_group%3A%2Flapidus&cols=service%2Cresource_name%2C%40duration%2C%40http.method%2C%40http.status_code%2C%40http.path_group&env=none&spanID=601201759987085071&topGraphs=latency%3Alatency%2CbreakdownAs%3Apercentage%2Cerrors%3Acount%2Chits%3Acount&start=1657287118214&end=1657290718214&paused=true)) 
List of hits to the home page shows it took between 5 and 13 seconds to load. @hackartisan notes it does not look like the type of bot issue we have had in the past. 

**Thoughts from @hackartisan & @sdellis:**

- It may help to reduce the number of search resulty that are returned on the collection homepage (UPDATE:  makes things a bit faster, but still unacceptably slow. 
- Lighthouse Chrome Extension (see screenshot below) provides some insight where we could improve. There is over 2mb of Javascript loading, which might not all be needed for the page/any pages and the server response time needs attention
- Datadog can see what is happening on the server side (the link above shows the trace), but will also require code analysis

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This does not currently impede work, but the site will be shown to the donor next Monday (July 11). It would be good to have it functioning semi-decently by then, and perfectly by official University Launch in Fall (@kelea99 will know the date of this after the visit on Monday).

### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [x] PO will prioritize  (recommendation: Maintence cycle 7 weeks from July 12)

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_
This site was built for a donor, who is being honored this year. The DPUL collection is something he was particularly interested in, as the digitization and global access/use of the collection as a research tool was a priority.
### Expected behaviour
When I click on the Lapidus Sticky on the home page of dpul, or a link to that home page of the exhibit, I expect that page to come up in less than 5 seconds.

### Actual behaviour
When I click on the Lapidus Sticky on the home page or a link to it, the home page take anywhere from 5-13 seconds to load.

### Steps to reproduce behaviour
go to: https://dpul.princeton.edu/princetoncollectors
Click on the Sid Lapidus Sticky (https://dpul.princeton.edu/lapidus)
wait

### Screenshots
<img width="1082" alt="Screen Shot 2022-07-08 at 10 40 20 AM" src="https://user-images.githubusercontent.com/45043014/178018873-67f597b7-21e9-434f-9d03-bf7d82a6bdc3.png">

**Comment by hackartisan** [comment]
The browse collection widget is taking a long time to query solr. You can see that the browse collection page itself loads quite slow. https://dpul.princeton.edu/lapidus/browse/browse-the-collection. One workaround would be to remove that widget from the exhibit home page. Another would be to reduce the default search results per page for the exhibit; that does make the widget load faster (though still not fast). You can see load time for the smaller set of search results by doing https://dpul.princeton.edu/lapidus/browse/browse-the-collection?per_page=10. Here's a datadog log search showing dpul prod solr query times: https://app.datadoghq.com/logs?query=service%3Asolr%20dpul%20-host%3A%28lib-solr-staging1%20OR%20lib-solr-staging3%29%20%40path%3A%22%2Fselect%22%20exhibit_lapidus_readonly_title_ssim&cols=%40QTime&index=&stream_sort=time%2Cdesc&from_ts=1657462094473&to_ts=1657548494473&live=true

query times are also slow for a blank search submitted through the search form.

Note the slow response is also observed in staging, https://dpul-staging.princeton.edu/lapidus and https://dpul-staging.princeton.edu/lapidus/browse/browse-the-collection

**Comment by tpendragon** [comment]
We ran the solr query locally on the solr box, and were finding run times of around 3 seconds. We're now not sure if that's the problem exactly, so we're going to get datadog running again and check the performance via APM.

**Comment by hackartisan** [comment]
In APM we saw that this home page is hitting solr twice. Presumably once for the facets and once for the embedded browse content.

**Comment by hackartisan** [comment]
Things we've investigated or thought about:

- Parent filter (for MVWs)
- The speed of solr: [APM example](https://app.datadoghq.com/apm/resource/dpul/rails.action_controller/892147145d819509?query=env%3Aproduction%20service%3Adpul%20operation_name%3Arails.action_controller%20resource_name%3A%22Spotlight%3A%3AHomePagesController%23show%22&env=production&event=AgAAAYOAE0bc4L_NnQAAAAAAAAAYAAAAAEFZT0FFMUxDQUFBb1Z0UlBUNW5CRmFBZQAAACQAAAAAMDE4MzgwMTMtNmNhNS00NTVkLWIyM2YtZWRkYTdlNGM1ZjBj&spanID=1943474858083886636&spanViewType=logs&timeHint=1664301090524&topGraphs=latency%3Alatency%2CbreakdownAs%3Apercentage%2Cerrors%3Acount%2Chits%3Acount&traceID=2206999600130823152&start=1664297740811&end=1664301340811&paused=true)
  - a curl command for timing this: https://gist.github.com/hackartisan/efd7cb381e80d0d96d719f33c0b871eb

**Comment by hackartisan** [comment]
The query times here are particularly slow and we believe it would take a rearchitecting of our indexing and retrieval process to improve them.

@kelea99 Is re-designing the exhibit home page an option? Removing the browse widget and the sidebar completely resolves the load time issue. Other widgets could be added in to showcase some of the content and/or direct users to search or browse results on a different page.

**Comment by kelea99** [comment]
@hackartisan  - lets talk through it more as you suggested and I can  then reach out to Will N. to talk about getting the long list of items on the home page changed to a recently added or highlights options.

**Comment by kelea99** [comment]
Closing this. I changed the DPUL main page and it loads great.
