### ISSUE TITLE
[DPUL/production] Riiif::ConversionError: Unable to execute command "identify -format '%h %w %m %[channels]' /opt/dpul/releases/20220713180040/public/uploads/spotlight/temporary_image/image/1627/Charles-Darwin-Overview-life-focus-evolution-work__2_.jpeg[0]"
identify-im6.q16: delegate failed `'dwebp' -pam '%i' -o '%o'' @ error/delegate.c/InvokeDelegate/1919.
identify-im6.q16: unable to open file `/tmp/magick-15245OGs1QuWsL7vU': No such file or directory @ error/constitute.c/ReadImage/544.

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#1381]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/86853494)

**Comment by hackartisan** [comment]
@kelea99 was someone trying to upload a Charles Darwin image? Does this need attention or everything is okay?

**Comment by tpendragon** [comment]
Someone uploaded a bad file we think.

**Comment by kelea99** [comment]
Wrote to/heard back from stakeholders. It has been erroring continuously for those two images. Im meeting with them next week to see what's up.
