### ISSUE TITLE
[DPUL/staging] NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#1401]
## Backtrace

    line 49 of [PROJECT_ROOT]/app/controllers/exhibits_controller.rb: decorate
    line 42 of [PROJECT_ROOT]/app/controllers/exhibits_controller.rb: find_exhibit

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/71710962)

**Comment by sdellis** [comment]
I noticed this was closed, but it continues to happen. Re-opening as it seems like something we can address.

**Comment by tpendragon** [comment]
Closed because this doesn't happen often and we're going to replace this application.
