### ISSUE TITLE
"Princeton Users: Log in to View" button is not showing up on "Princeon Only" Visibility  "Ephemera Project" Scanned Resources

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1402]
### Summary
As an answer to three user needs, we decided to test out providing restricted access to curated collections via DPUL unpublished exhibitions. The items being mapped to DPUL are "Princeton Only" Visibility.   

What works:

- Users can sign in to DPUL and are able to view the unpublished collections they have been added to as "viewer". 
- Users can see thumbnails and metadata of the scanned resources marked "Princeton Only"

What does not work:
- Users cannot see the full resource. when the thumbnail is clicked, they navigate to a page with a blank square where the viewer should be.  The "Princeton Users: Log in to View: button does not appear (see screenshots). *

*We know this functionality works in DPUL, thanks to the Performance Audio Archive Collection (see screenshots).  However, it is not working for the ephemera project resource example for  https://dpul.princeton.edu/eal_covid-19_posters

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This workflow is going to be used for a forthcoming class with Sara Howard. She will be using her LGBTQIA+  DPUL colleciton as specified above: https://dpul.princeton.edu/lgbtqia_ephemera

### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [x] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_
This is a sudden priority only because we do not yet have the harmful/illicit content click throughs in place yet. If those are coming soon and we have an ETA, i can touch base with the stakeholders and confirm options. 

### Expected behaviour
As a "viewer" user to an unpublished DPUL site, I expect to be able to click on a thumbnail of a "Princeton Only" item, navigate to that item in DPUL, and see a blue "Princeton Users: Log in to View" button where the viewer should be (above the metadata).  Once I log in, I expect to see a viewer that shows the item i am interested in viewing.

### Actual behaviour
As a "viewer" user to an unpublished DPUL site, I click on a thumbnail of a "Princeton Only" item, navigate to that item in DPUL, and see blank grey-taupe square where the viewer should be (above the metadata).  

### Steps to reproduce behaviour

1. Go to https://dpul.princeton.edu/eal_covid-19_posters as a viewer user (the site is unpublished, so you will need to be added as a viewer in order to see it as one. OR temporarily publish the site, open up the link in a incognito window, and go through following steps).
2. Click on thumbnail of a poster
3. What do you see?
![Screen Shot 2022-10-07 at 2 53 54 PM (2)](https://user-images.githubusercontent.com/45043014/194637884-1231acda-7075-4892-8725-f2cd852149b2.png)
![Screen Shot 2022-10-07 at 2 54 22 PM (2)](https://user-images.githubusercontent.com/45043014/194637920-ed0fbb8c-73c0-4c06-a6c8-ae9442dbd6cd.png)

**Comment by eliotjordan** [comment]
@kelea99 This appears to be fixed. I'm going to close this. If you discover issues, please re-open.

![Screenshot 2023-04-05 at 11 20 26 AM](https://user-images.githubusercontent.com/784196/230143315-c2b881da-86a3-4f4a-8796-8e32aff7f287.png)
