### ISSUE TITLE
Takedown Private Complete items from Grounds and buildings collection ( https://dpul.princeton.edu/ac111) 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1403]
### Summary
Private scanned resources without images were accidentally completed in figgy and need to be taken down. These items were used for a specialized use case that was taken down in place of item level ingest of items available solely in DPUL. 

Collection of Private, Complete items that need to be marked as "Takedown":  https://dpul.princeton.edu/ac111

Link to search:  https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Historical+Photograph+Collection%2C+Grounds+and+Buildings+Series&f%5Bvisibility_ssim%5D%5B%5D=restricted&q=Grounds+and+buildings

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This is not hindering work. It may be confusing to users of the FA site, with a bit black viewer and no items within. Brought to my attention by @tpendragon 

### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_

**Comment by hackartisan** [comment]
The only item in that collection is marked "open" in figgy; it looks like this was resolved somewhere along the way.
