### ISSUE TITLE
Arabic text display does not float/anchor to the right

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/dpul#1408]
For example:

<img width="1176" alt="Screen Shot 2022-11-07 at 11 46 08 AM" src="https://user-images.githubusercontent.com/999701/200302452-b64ddb0f-7bb3-4bf9-a491-fb366e1896b9.png">

**Comment by jpstroop** [comment]
The font should also be calligraphic rather than block

**Comment by eliotjordan** [comment]
Might need to move the "Edit" button and add some styling.

**Comment by kelea99** [comment]
Font request has been made into a new ticket:  #1417
