### ISSUE TITLE
DPUL Exhibits showing title only issues at end of browse all category

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1433]
### Summary

Lapidus DPUL exhibit is showing the title only ingests for MVWs (child volumes) at the end of the all search/browse all listing. This was a bug in the past. See screenshot as well.

https://dpul.princeton.edu/lapidus/feature/browse-the-collection?page=57

### Thoughts
1. attempt a reindex on monday to see if that fixes the issue. if not...
2.  have a look at the closed ticket for similar (same?) issue: https://github.com/pulibrary/dpul/issues/362

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This is a high profile exhibit that was recently highlighted in university articles about the Donor.
### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_
High-profile DPUL exhibit.

### Screenshots
<img width="1512" alt="Screen Shot 2023-02-11 at 2 32 09 PM" src="https://user-images.githubusercontent.com/45043014/218277732-7b7aeae4-c700-4e67-97e0-e5f330d79879.png">

**Comment by sdellis** [comment]
Possible fix: We could remove collections from children for the Lapidus collection. Parents are not in collections and are not getting indexed. 

Example: https://figgy.princeton.edu/catalog/289a9501-f031-41ba-84b2-b9121fde5c13
Parent: https://figgy.princeton.edu/catalog/1000ce02-8e21-4527-8ebc-128ea673822d

**Comment by tpendragon** [comment]
I'm kicking off a reindex, but this should be fixed.

**Comment by kelea99** [comment]
Looks great, @tpendragon ! Closing ticket.
