### ISSUE TITLE
Error indexing a resource into DPUL

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/dpul#1442]
[DPUL/production] Psych::DisallowedClass: Tried to load unspecified class: IIIF::OrderedHash 

https://figgy.princeton.edu/catalog/d52aa68c-6fb4-4afc-8398-dd9dd503b04f

## Backtrace

    line 87 of [PROJECT_ROOT]/app/services/iiif_manifest.rb: add_metadata
    line 15 of [PROJECT_ROOT]/app/services/iiif_manifest.rb: to_solr
    line 58 of [PROJECT_ROOT]/app/models/iiif_resource.rb: reindex

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/95028217)

**Comment by eliotjordan** [comment]
Fixed by https://github.com/pulibrary/dpul/pull/1444

**Comment by hackartisan** [comment]
Error still occurring

**Comment by hackartisan** [comment]
stackoverflow suggests we should add the class to https://github.com/pulibrary/dpul/blame/0dfca59508dbb7d6e5b3fd26ea763712c2957b58/config/application.rb#L35
