### ISSUE TITLE
Upgrade Redis

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul#1456]
We have a local install of Redis for DPUL. It's on 4.0.9

See https://github.com/pulibrary/princeton_ansible/issues/2799

**Comment by hackartisan** [comment]
Steps:

* find the sidekiq upgrade branch created by dependabot. run `bundle up sidekiq-pro` if the project uses sidekiq pro. Update the lando config to use redis 7. Update the sidekiq configuration. example PR: 
* turn off workers for the app
* once https://github.com/pulibrary/princeton_ansible/pull/4284 is merged, run the app's usual ansible playbook, then run the upgrade_redis playbook.
* deploy the sidekiq upgrade branch

**Comment by hackartisan** [comment]
It's been upgraded to 7.2.1.
