### ISSUE TITLE
Remove brackets and quotes in diplay of text links for supplemental materials in DPUL

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1457]
### Summary
The links to supplemental materials in the records in DPUL are displaying with brackets and quotes:  [”  ‘’]. what i see in edit:
<a href=‘https://arks.princeton.edu/ark:/88435/dc2j62sg20c’>[“A complete program is available in online here”]</a>
Could we easily nix the brackets and quotes from the display? it views fine in the online catalog. Example:
DPUL: https://dpul.princeton.edu/performances/catalog/6f42ab87-5930-4d08-a108-78fb0ab25755
Online catalog: https://catalog.princeton.edu/catalog/99114274333506421

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This is not stopping work, but is a painpoint for Mendel stakeholders.  It also does not reflect the metadata display that is in orangelight.
### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_
This is affecting all of Dan's work with the Concert Programs linked to the sound recordings.  DPUL is the primary discovery point for this material, so we should have a clean display of the metadata.

**Comment by hackartisan** [comment]
build on https://github.com/pulibrary/dpul/commit/7ef03f756e2175fed53c72a499c91895f9e2ca78

**Comment by hackartisan** [comment]
This resource is indexed into performances and music. Both those collections will need to be reindexed. @kelea99 or @tpendragon do you think there are any other collections that will need to be reindexed once the fix is deployed?

**Comment by hackartisan** [comment]
reindexed those; this is done
