### ISSUE TITLE
Remove 2 spotlight resources/iiif harvesters in DPUL site

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1465]
### Summary
Two items were added in the dashboard via  Curation>Items>Add Items>IIIF URL (the IIIF URLs are from the Lilly Library Site). These items need to be deleted.  Can someone remove those? I cannot find a way to do so on my end.
https://dpul.princeton.edu/1762-archive/catalog?f%5Bspotlight_resource_type_ssim%5D%5B%5D=spotlight%2Fresources%2Fiiif_harvesters

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
Sometime this summer
### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_
This is for a project that student Evan Ditter is working on for Anu

**Comment by tpendragon** [comment]
End goal is those two resources are gone (IIIFResource deleted in the database, and the items removed from the index)
