### ISSUE TITLE
[DPUL/staging] RedisClient::ReadTimeoutError: Waited 2.0 seconds

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul#1484]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/100537395)

**Comment by tpendragon** [comment]
Looking at https://github.com/sidekiq/sidekiq/wiki/Using-Redis to see if it has any advice.

**Comment by hackartisan** [comment]
closing in favor of #1487
