### ISSUE TITLE
dpul:reindex:collections does not appear to fully reindex collections

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1491]
### Summary
Reported by @tventimi (#1488 ) and Ellen Ambrosone (SAE). may be similar to #1294 . maybe also look at #1395 , just in case.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks - before winter break
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_
Good to have everything fully available to folks by winter break, before we are a skeleton crew. 

Researchers will use these collections over winter break and if this isn't fixed there will be missing content that will prevent them from finishing their research - and we won't have staff to perform the workaround.

### Steps to reproduce behaviour

Go to the ukrainian-art collection, hit "reindex all", go to it in Figgy, compare the count of resources in each set of search results. They won't match. Check honeybadger? Check sidekiq? Check indexing errors in DPUL.

## Examples
Figgy counts below are faceted to complete resources only.

Ukranian Art in Times of war (an ephemera project):
- Figgy count is 142: https://figgy.princeton.edu/?f%5Bephemera_project_ssim%5D%5B%5D=Ukrainian+Art+in+Times+of+War%3A+2014-&f%5Bstate_ssim%5D%5B%5D=complete&parent_id=4d7207cf-d81e-4f4e-956c-b2028c8edbb7
   - manifest: https://figgy.princeton.edu/concern/ephemera_projects/f384bc51-6aad-49c6-b5f2-d671aa275310/manifest
- dpul count is 142: https://dpul.princeton.edu/ukrainian-art/catalog?utf8=%E2%9C%93&exhibit_id=ukrainian-art&search_field=all_fields&q=

Treasures of the East Asian Library (a collection):
- Figgy count is 937: https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Treasures+of+the+East+Asian+Library&f%5Bstate_ssim%5D%5B%5D=complete
  - manifest: https://figgy.princeton.edu/collections/f293aebb-3f3e-4463-9239-322ab93bde52/manifest
- dpul count is 834: https://dpul.princeton.edu/eastasian/catalog?utf8=%E2%9C%93&exhibit_id=eastasian&search_field=all_fields&q=

Slavic DPUL Exhibit (a collection):
- Figgy count is 6317: https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Princeton+Slavic+Collections&f%5Bstate_ssim%5D%5B%5D=complete
- dpul count is 6065: https://dpul.princeton.edu/slavic/catalog?utf8=%E2%9C%93&exhibit_id=slavic&search_field=all_fields&q=

**Comment by sdellis** [comment]
Reels of microfilm in Tom's collection don't seem to get indexed.

**Comment by tpendragon** [comment]
We're going to mark this as a sudden priority and work it, understanding that it might be hard to get it done in a specific timeline.

**Comment by hackartisan** [comment]
There's an indexing error from honeybadger here that I'm not sure is related but I thought worth dropping a link. The collection producing those errors has a couple of reindexing attempts with status "not yet started" https://dpul.princeton.edu/ukrainian-art/dashboard

**Comment by hackartisan** [comment]
I just added some more specific links to the steps to reproduce. Currently the Ukraine art counts look right.

**Comment by hackartisan** [comment]
the redis port was closed on dpul1 and dpul2 could not connect. there were a bunch of errors related to this in datadog. This may have been the issue if dpul2 happened to be the machine that tried to enqueue the exhibit reindex. This has been resolved and I'll try reindexing the affected collections now.

**Comment by hackartisan** [comment]
All the counts for the collections cited are now correct. If any other counts seem off, reindexing the collection via the dpul admin interface should resolve it. We could kick off a reindex for all dpul collections. If that's desired, feel free to request it by reopening this ticket with a comment to that effect.
