### ISSUE TITLE
Provision Jammy VMs

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#1493]
# Reasoning

We need to upgrade all our boxes to Jammy; we're starting to be unable to get apt packages, etc.

# Boxes to Migrate

These are the names of the existing boxes. We can change the names to use current conventions, suggestions inline.

## Staging
`dpul-staging1` => migrate to `dpul-staging3`?
`dpul-staging2` => migrate to `dpul-staging4`?

## Production
`dpul1` => migrate to `dpul-prod1`
`dpul2` => migrate to `dpul-prod2`

**Comment by acozine** [comment]
Existing dpul-staging boxes have:
16 GB of memory
40 GB hard drive
dpul-staging1 has 4 CPUs; dpul-staging2 has 2 CPUs

I made the new staging boxes with 4 CPUs, 16GB mem, and 30GB drives.

Existing dpul production boxes have:
2 CPUs
32 GB of memory
40GB hard drive

I made the new prod boxes with 4 CPUs, 32GB mem, and 30GB drives.

VMs are all done, they just need firewall rules added.

**Comment by acozine** [comment]
Jammy DPUL boxes are all ready to go. They currently have `lib-vm` as the hostname, but running the playbooks will fix that. Let me know if you run into any issues.

**Comment by acozine** [comment]
Hint for Future Me - in each environment, only one VM needs port 6379 open for Redis as well as the usual SSH, HTTP/HTTPS ports.

**Comment by tpendragon** [comment]
We're reopening these, but just so we can keep track of doing the provisioning of these now that they're made.
