### ISSUE TITLE
2 resources viewing in DPUL exhibit that cannot be found in Figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1494]
### Summary
two items: 
1.  [07893_reel_26](https://dpul.princeton.edu/spanish_transition/catalog/dcf4752v341)
2.  [07893_reel_26A](https://dpul.princeton.edu/spanish_transition/catalog/dc9p290n94r)

From:
https://dpul.princeton.edu/spanish_transition/catalog?per_page=100&q=&search_field=all_fields&sort=sort_title

This may need to be moved to figgy repo.  Items above are not to be in this exhibit. I cannot find them anywhere in Figgy. 
1. deleted? 
2. Issue with child being given collection tag? 
3. just a bug?

When found:
1. delete from DPUL exhibit
2. Delete from figgy
### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize - after holiday

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_

**Comment by tpendragon** [comment]
These are real, but we'll have to use the console to remove the collection from them since we removed that from the UI for child works.

**Comment by tpendragon** [comment]
All gone.

**Comment by kelea99** [comment]
Thank you! I let Kim M (she took over for Natalie) and Fernando know!
