### ISSUE TITLE
Thumbnails for ephemera project not displaying in DPUL, but are displaying fine in Figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1496]
### Summary
Reported by Anna Meerson for Ukranian Art 2014- Figgy Project
Example: https://dpul.princeton.edu/ukrainian-art/catalog?utf8=%E2%9C%93&exhibit_id=ukrainian-art&search_field=all_fields&q=
I tried a reindex of site to pull in missing items from figgy last week. reindex did not work for pulling in missing items, and also dropped the thumbnails.
Tried a reindex again today at ~11:30am. no luck.

Seems different than [Figgy #6081](https://github.com/pulibrary/figgy/issues/6081), but perhaps related to the fix that was done? I wonder. Both affected the ephemera project thumbnails.  I could test a reindex of another ephemera project in dpul to see if it drops the thumbnails, but Im not sure any of us want me to do that before holiday. 

i have shared with Anna that the reindex is being worked on, but this thumbnail issue would have to wait until after the holiday.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [x] PO will prioritize after holiday break 2023

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_

**Comment by kelea99** [comment]
Figured it out! looked in "General" in Dashboard, trying to see what was clicked on off/ selected/etc... as a last resort.  thumbnails were disabled!! Closing ticket.

**Comment by hackartisan** [comment]
Wow good find @kelea99
