### ISSUE TITLE
Migrate Solr Staging from lib-solr8-staging to lib-solr8-d-staging

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul#1508]
Sub-ticket of https://github.com/pulibrary/princeton_ansible/issues/4666

**Comment by hackartisan** [comment]
closed by https://github.com/pulibrary/princeton_ansible/pull/4768

**Comment by hackartisan** [comment]
Seems like this is still in progress

**Comment by hackartisan** [comment]
It's hooked up now and the index is populating.
