### ISSUE TITLE
Delete 2 DPUL uploaded items causing errors in DPUL exhibit "treasures of the east asian library"

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1509]
### Summary
2 items: [12-249897](https://dpul.princeton.edu/eastasian/catalog/12-249897) & [12-249896](https://dpul.princeton.edu/eastasian/catalog/12-249896) were uploaded using the feature in DPUL's dashboard within "Items". They need to be deleted.  This is kinda like those iiif manifests that were also added in dashboard a while back. 

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [x] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_

**Comment by kelea99** [comment]
maybe similar to this? https://github.com/pulibrary/dpul/issues/1465

**Comment by hackartisan** [comment]
The links are giving a 404 so I think this is done; closing.
