### ISSUE TITLE
Add Plausible.IO

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul#1532]
## Acceptance Criteria

- [x] There's a section in Plausible for DPUL
- [ ] Initial metrics are being gathered for DPUL.

**Comment by hackartisan** [comment]
Here are some instructions that RDSS wrote up: https://github.com/pulibrary/rdss-handbook/blob/main/plausible.md

They say that we have to make the organizational cardholder the "owner" of our site/s for them to be included in PUL's plan. This appears to be a process requiring the cardholder to respond to 2 separate emails from plausible's systems. Who is the cardholder? Is that Tracy?
