### ISSUE TITLE
Track count of record pages per visit

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul#1534]
We want to know how many individual records a person tends to visit per session. Record pages are pages like "/catalog/123".

## Acceptance Criteria

- [ ] If a user visits /catalog/123 and /catalog/234 in a session there's an easily displayed metric that shows the number of records visited in that session was 2.

## First Step

- [ ] Fiddle around in Plausible and see if you can filter to just record pages, document how.

**Comment by tpendragon** [comment]
I can get how many visits there are to a record page, and can even create a goal for it, but I can't get Plausible to tell us how many times a person tends to visit that page in a session.

I created https://feedback.plausible.io/423 to request that feature.

**Comment by tpendragon** [comment]
If we add a property to the page view event for record pages, I think we can filter to just those and maybe get "Views per Visit"

**Comment by sdellis** [comment]
In Plausible we can apply a filter to show only record pages by clicking on the Filter button, click`Page`, select `Page Contains`, and type "catalog/", and apply the filter. This gives us information on records that have been viewed. This is different from the Acceptance Criteria which asks for how many unique records a user visits per session. Plausible doesn't seem to give information about individual user behavior, but we could potentially have an opaque id for a user and send it along with their record views per session to Plausible for aggregation. That seems to be the next step.

**Comment by sdellis** [comment]
We can't track any Personally Identifiable Information about an end user, but we can send both the Session ID and the record page/id to plausible.
