### ISSUE TITLE
Fix Alternative title mapping to allow for multiple alt titles to be viewed.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1587]
### Summary

What seems to be happening in current state:
1. Items with ONE alternative title entry (this also means items that do not have a blank additional field in figgy) are shwoing that alternative title in DPUL for the item.
2. Items with more than one alternative title entry in figgy (this also means items that have a blank additional field for alternative title in figgy) are not showing any alternative title in DPUL. even the field in the edit form for items in DPUL show the "alternative title" field as being blank.

We need any and all alternative titles to view in DPUL.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_
Needed for soft launch of Pakistani film posters site. @ellen-aa  is primary stakeholder.
### Expected behaviour
when i go to an epehemera item in DPUL, like the Pakistani film posters site, I expect to see any and all entries for alternative title field.

### Actual behaviour
when i go to an epehemera item in DPUL, like the Pakistani film posters site, I  see alternative titles for items that have only one alternative title entry in the figgy form. I see zero alternative titles for items that have more than one alternative title entry in figgy. 

### Steps to reproduce behaviour
go to: 

### Screenshots
ONE alt title (golden Girl) - Visible!:
<img width="1512" alt="Screenshot 2024-12-04 at 5 34 38 PM" src="https://github.com/user-attachments/assets/e2707016-5f14-4909-8c51-7269cb0bb26f">
<img width="1512" alt="Screenshot 2024-12-04 at 5 34 47 PM" src="https://github.com/user-attachments/assets/cf065e07-f5a9-47f7-a394-24bd45fa3d7c">

Two alt titles (one field is blank) Kundan - not visible!:
<img width="1512" alt="Screenshot 2024-12-04 at 5 34 38 PM" src="https://github.com/user-attachments/assets/8c9e8b7e-466b-47f4-9991-e0b503560432">
<img width="1512" alt="Screenshot 2024-12-04 at 5 35 54 PM" src="https://github.com/user-attachments/assets/69eeb0ba-dcdc-44c7-9dad-36521c521958">

## First Step

Write a test.

**Comment by kelea99** [comment]
Fascinating. after a reindex of the site,  zero alt titles are showing at all.

**Comment by kelea99** [comment]
### Item Level Records in Figgy/DPUL example

- Link to Item level record in DPUL:  (Goldan Garl - alt title "golden girl" not showing - also look within edit form - the field name is there, but a blank space where "golden girl" should be): https://dpul.princeton.edu/pakistani-film/catalog/a35210e4-0159-4669-94d3-f451fdf553a2
- Link to item level record in Figgy (Golden Girl/Goldan Garl): https://figgy.princeton.edu/catalog/a35210e4-0159-4669-94d3-f451fdf553a2

**Comment by kelea99** [comment]
All search example in DPUL (I have the list view "alternative title" activated, so if t here is one or more it should be showing in the all search metadata)
https://dpul.princeton.edu/pakistani-film/catalog?utf8=%E2%9C%93&exhibit_id=pakistani-film&search_field=all_fields&q=

**Comment by kelea99** [comment]
### Item Level Records in Figgy/DPUL example 02 (with 2 entries for alternative title!)

- Link to item level record in DPUL: https://dpul.princeton.edu/pakistani-film/catalog/e363c8e5-6353-405a-aeb4-212d7c36b024
- Link to item level record in Figgy (Jagga te Reshman/Juga te Reshma/Jagga tey Reshma):  https://figgy.princeton.edu/catalog/e363c8e5-6353-405a-aeb4-212d7c36b024

**Comment by hackartisan** [comment]
I added these two examples to the dpul sync test collection and reindexed on staging. It seems like they show up as expected. https://dpul-staging.princeton.edu/dpul_sync_test/catalog?utf8=%E2%9C%93&exhibit_id=dpul_sync_test&search_field=all_fields&q=

**Comment by ellen-aa** [comment]
Hi there, I can't open the link in DPUL staging. @hackartisan

**Comment by hackartisan** [comment]
> Hi there, I can't open the link in DPUL staging. @hackartisan

Hi ellen! I'm mostly taking notes to myself, seems like a data issue on this collection, still working on it!

**Comment by tpendragon** [comment]
We found that the problem could be replicated by renaming the field "Alternative" to "Alternative title" in the UI.

It has something to do with a mismatch between that label and the field label in the JSON-LD coming from Figgy.

We think if this is true, then whenever a field got renamed in the UI and then reindexed it would have dropped that field so we're a little surprised we haven't seen this before and think maybe we're missing something.

Code mismatch we're seeing is here:

This says only add things that have matching labels to custom fields

https://github.com/pulibrary/dpul/blob/379190695c4c1a5903ee8315caf021bc5eb8876d/app/services/iiif_manifest.rb#L118

This says only create custom fields that don't already exist based on the slug.

https://github.com/pulibrary/dpul/blob/379190695c4c1a5903ee8315caf021bc5eb8876d/app/services/iiif_manifest.rb#L150-L153

We think we might be able to fix this by using the slug in both cases.

**Comment by hackartisan** [comment]
fix deployed and collection reindex
