### ISSUE TITLE
Limit collection description length

### ISSUE THREAD

**Issue by axamei** [pulibrary/dpul#275]
Currently overflows and users need to scroll. Descriptions should be brief/concise. 

<img width="258" alt="screen shot 2017-06-01 at 9 38 32 am" src="https://cloud.githubusercontent.com/assets/8161144/26686786/07ea758e-46bc-11e7-8797-72f184fc3c31.png">

Child of #440

**Comment by sdellis** [comment]
It would be nice if there was some visual indication to the person entering the description (similar to how Twitter tells you your tweet is too long).

**Comment by jpstroop** [comment]
@joycebcat is there any reason we can't make the abstracts on these card a little more concise?

**Comment by joycebcat** [comment]
Heh, heh, heh.  I encouraged, suggested, mentioned, repeated, and encouraged again having short descriptions that didn't require scrolling.  Sandy took the bait and hers are really short.  Don S obviously did not.  I could go back and try again.

**Comment by hackmastera** [comment]
A workaround is to hand-edit the text for the ones that are too long
