### ISSUE TITLE
List of Spotlight implementers

### ISSUE THREAD

**Issue by escowles** [pulibrary/dpul#412]
* Steve Ferguson asked for a list of Spotlight implementers

**Comment by tpendragon** [comment]
@escowles It's been...a while. We could still follow up with this, but does Steve still want this list?

**Comment by escowles** [comment]
Probably not — but "who else is using Spotlight?" seems like a question we should be able to answer.  I only see three orgs on the [Spotlight wiki](https://github.com/projectblacklight/spotlight/wiki/Examples-and-demos) (us, Stanford, and UVic), but there are [44 repos using Spotlight](https://github.com/projectblacklight/spotlight/network/dependents?package_id=UGFja2FnZS0xMDY0MDM%3D), so I think there are probably at least a few more we could find.  At a minimum, figuring out if the Columbia, Cornell, UC, Indiana, and/or Oregon ones are in production would be good.

**Comment by hackmastera** [comment]
Maybe we could just make a page on the spotlight wiki and post a message in slack asking people to add themselves. Spotlight community group has a monthly call; this would be good to bring up there.
