### ISSUE TITLE
Make favicon transparent

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/dpul#428]
Small thing, but the macOS dark mode making it more noticable:

<img width="78" alt="screen shot 2018-10-03 at 11 50 51 am" src="https://user-images.githubusercontent.com/999701/46432329-e58ec080-c702-11e8-9f5b-6c00ccaba180.png">

**Comment by hackmastera** [comment]
@escowles Who should be consulted here?

Should we use the one on the library site? If we change it it should be across the board for all our sites.

**Comment by escowles** [comment]
@hackmastera I would be fine with using the Library favicon if @kelea99 is fine with it — but it also seems worth asking @axamei if we should switch all of our apps to using the Library website favicon, or if we should make the DPUL/Figgy/OL one transparent and use it everywhere instead.

**Comment by axamei** [comment]
@escowles We should probably have a consistent favicon that more closely resembles the new Library logo: I can help create some these assets if needed.

<img width="97" alt="Screen Shot 2020-01-27 at 4 30 47 PM" src="https://user-images.githubusercontent.com/8161144/73215687-9142f780-4122-11ea-820b-9d47f75ee14d.png">

**Comment by kelea99** [comment]
@escowles and @axamei  I am fine with what Axa would recommend with this.

**Comment by axamei** [comment]
@escowles @kelea99 I've added some files in https://drive.google.com/drive/folders/1xCcUmSxtGS1u6we9FW_QQM46x8FQw4wj
