### ISSUE TITLE
Firefox freezes in edit mode

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/dpul#654]
> DPUL is having issues when using Firefox as the browser.  It stalls and freezes in edit mode when attempting to change a multi row grid thrumbnail (ex: https://dpul.princeton.edu/marquand/home/edit.marquand-library-of-art-and-archaeology). Its also super slow when editing text at the moment.

Reported by @kelea99.  

Was able to replicate this issue. Inspector and web console don't return anything.

**Comment by hackmastera** [comment]
For now using another browser is an acceptable workaround

**Comment by hackartisan** [comment]
This is no longer happening.
