### ISSUE TITLE
db:create errors

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#676]
`PG::ConnectionBad: FATAL:  database "dpul_development" does not exist`

Had to run `createdb dpul_development`

This is probably setup-specific and I'm not sure why my homebrew-installed postgres couldn't/didn't do this for me. But if others run into it it might be useful to add to the readme.

**Comment by jrgriffiniii** [comment]
I have encountered this when attempting to invoke `db:drop` and `db:setup`, but for https://github.com/pulibrary/figgy. Prior to today (04/23), this was never required in my macOS environment (10.14.5).

**Comment by hackartisan** [comment]
we have lando now; I don't think this is an issue anymore
