### ISSUE TITLE
I would like to custom organize the sort for items within item list or gallery view in a saved search with an option to display as the default 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#697]
3 uses cases (requests from the curators) so far for the Milberg gallery DPUL exhibits, regarding requested organization of items viewed within saved searches for the site. while one request could be addressed in some way with a recent enhancement (date options for both ascending and descending), others (such as the coins from WA and the most recent Picturesque exhibit, where a curator wishes for a specific aesthetic ordering of subcategories, which is not possible with any metadata associated with it now) are not. Would it be possible to create a hidden field that would function as a ranking system of sorts, that could be used as the default sort order of the saved search? this would eliminate having to continue adding sort options. What do you think?

As a curator I want to create a custom sort order for my dpul collection so that I can present the items in the order they appear in the physical exhibit.

**Comment by hackmastera** [comment]
@kelea99 can you spell out one or two of the use cases more specifically?

You're asking for the sort order to be associated with a specific saved search. I can't tell how closely tied that is to the requirement. Are you asking for a given collection to be able to have multiple different custom orderings?

**Comment by kelea99** [comment]
@hackmastera Ideally? it would be nice to have that flexibility. realistically and what would probably be mostly (if not entirely) needed? creating an overall sequencing for the collection at large, that would also correspond to the order of the sub collections that I create via tagging or collection tags in figgy and then saving the search in DPUL, would work.
![Custom_Sort_Example](https://user-images.githubusercontent.com/45043014/72932425-c8359980-3d2d-11ea-8178-e854a9b129e5.png)

**Comment by hackmastera** [comment]
Based on conversation with @kelea99:

This can be implemented globally with one (optional) custom sort order per collection.

The user does not need to be able to make the custom sort order the default for search.

In order to create the desired browse category, submit an empty search, select the custom sort order, and save the search. Then turn it on as a browse category.

**Comment by kelea99** [comment]
Closing this. DPUL 3.0 allows for organization of items in custom order by site builders.

**Comment by hackartisan** [comment]
yay!
