### ISSUE TITLE
Two collections have the same slug in figgy

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#727]
'lae' is used for the ephemera collection https://figgy.princeton.edu/catalog/d7c889ba-9992-494e-8fe4-2c4a9b3c3d7d and the poster collection.

**Comment by hackmastera** [comment]
This causes problems with syncing.

**Comment by hackartisan** [comment]
There is now only one entry with "lae" -- not sure if the poster collection is still a thing? but regardless there's only one "lae" in https://figgy.princeton.edu/iiif/collections

**Comment by kelea99** [comment]
Checked with stakeholders on this one. The posters are being integrated into LAE and the old DPUL exhibit for them is no longer a thing.
