### ISSUE TITLE
Suddenly returned to collection home when trying to add image to widget

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#728]
Reported by Thomas K. re: Princeton Slavic Collection and 

To replicate:

1. Go in to edit the widget from the collection page.
1. Type a title in the search box, e.g. "zrelishcha"
1. If the search box resolves to bring up the item (which doesn't always happen), you don't get a chance to select it and save before suddenly the collection home loads with a flash message that the changes have been applied. However, they have not been applied. If you do successfully click on a single-page object the save button does not become actionable (it stays inactive so you can't click on it).

Browser: Chrome

Note that these pages load very slowly. Related?

**Comment by kelea99** [comment]
Testing this in other browsers needed. @kelea99 will do. If another browser works, its at least a temporary fix and makes this less of a priority.

**Comment by hackartisan** [comment]
Can't replicate now. And all widgets were thoroughly tested during the spotlight 3 upgrade.
