### ISSUE TITLE
Font overflow on home page

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/dpul#765]
My browser dimensions are 1027 x 399px

<img width="1051" alt="Screen Shot 2020-04-07 at 2 54 34 PM" src="https://user-images.githubusercontent.com/999701/78708244-d2ecdd00-78df-11ea-9dff-d0322af96493.png">

**Comment by kelea99** [comment]
Checking browsers, @jpstroop. Image isn't broken for me in Safari or Chrome, but is missing in Firefox. need to boot up other computer for Brave.

**Comment by hackmastera** [comment]
I made https://github.com/pulibrary/pomegranate/issues/767 for the missing image problem. Updating this issue to just be about the font overflow.

**Comment by hackartisan** [comment]
The front page cards were redone and checked at all screen sizes.
