### ISSUE TITLE
Embed widget broken for multi volume works

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#769]
Encountered while working on a new exhibit https://dpul.princeton.edu/shibui.

Page for the book "Nanshoku okagami/ Mirror of Male Love" is causing this error.

[Pomegranate/production] ActionView::Template::Error: key not found "tile_source_ssim"

## Backtrace

    line 25 of [PROJECT_ROOT]/app/models/solr_document.rb: fetch

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/62921650)

**Comment by hackmastera** [comment]
This is a bug with the item embed widget for multi volume works.

**Comment by eliotjordan** [comment]
This appears fine now.

**Comment by eliotjordan** [comment]
Not fine. The "item embed" widget does not work for MVW items. Example:

https://figgy.princeton.edu/catalog/317ae996-c459-4482-9d33-6571313a26d7

![Screen Shot 2021-11-09 at 4 21 45 PM](https://user-images.githubusercontent.com/784196/141015434-331c2129-2c7f-4968-b516-276ee9bd8d14.png)
![Screen Shot 2021-11-09 at 4 21 57 PM](https://user-images.githubusercontent.com/784196/141015439-75c84d93-5247-49f4-901a-3d29bd9101f3.png)

**Comment by eliotjordan** [comment]
Guessing it has something to do with indexed MVW records:
https://github.com/projectblacklight/spotlight/blob/f1169e19631e2c79c88648ca310375634739e405/app/models/spotlight/resources/iiif_manifest.rb#L123

**Comment by kelea99** [comment]
@eliotjordan, if it helps, MVW thumbnail selection did not work in the old DPUL either. I remember running into it when I first started learning about DPUL and selecting images for banners/etc...

**Comment by kelea99** [comment]
Would be really great to get this to work, if we can. It opens up options for the growing number of MVWs in the collection.
