### ISSUE TITLE
Upgrade to Solr 8

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul#822]
Note that this migration requires advance notice to users since synchronization from figgy will be down for the duration.

This would close #675 

Should #706 be a pre-requisite so we don't end up in that situation again? [Update: #706 is done]

Steps: 
- [x] Validate a verification strategy for ensuring the index completed fully
  * e.g. tunneling to the machine that's off the load balancer and comparing a search results count with the machine that's still serving the old index
- [x] Create dpul-production collection on solr8 box
- [x] Turn off one node's access from the load balancer. -- Make sure no one runs the load balancer playbook during this time!
- [x] Turn off sneakers workers on both boxes
- [x] Point the machine that's been taken off the load balancer at the solr 8 box
- [x] turn off sidekiq workers on the box that's still serving web traffic. double sidekiq workers on the other one.
- [x] Run the reindex from the solr 8 box
- [x] run through the verifiation strategy
- [x] Switch the load balancer and check the new index
- [x] Update configuration so that both boxes point to solr 8
- [x] Turn back on the node balancer for both
- [x] Turn all workers back on.

Relevant PRs:

https://github.com/pulibrary/pul_solr/pull/237
https://github.com/pulibrary/princeton_ansible/pull/1748

**Comment by bess** [comment]
Update at end of day 12 July:
* dpul-staging config has been updated to solr8 
* Next steps:
  * pul_solr needs to be deployed to solr8
  * dpul-staging needs to be redeployed
  * dpul-staging needs to be reindexed

**Comment by hackartisan** [comment]
We'll do this on the next cycle, the week of Feb 7

**Comment by hackartisan** [comment]
Blocked by #1294

Also complicated by:
- #1295
- #1291

Once we feel confident in the full reindex, time it again. Remember that during this migration we'll only have one machine doing indexing. Consider increasing the number of workers it's running temporarily.

**Comment by hackartisan** [comment]
Here's an index count validation strategy:

```
new_index_counts = Spotlight::Exhibit.all.map{ |e| [e.id, e.resources.count]
}.to_h.sort
# Do the same on the machine connected to the old index and copy/paste it into `old_index_counts`
counts_zip = new_index_counts.zip(old_index_counts)
counts_zip.each do |tt|
  if tt[0][0] == tt[1][0] && tt[0][1] == tt[1][1]
    puts "e #{tt[0][0]} equal"
  elsif tt[0][0] == tt[1][0]
    puts "e #{tt[0][0]} staging count #{tt[0][1]} prod count #{tt[1][1]}"
  else
    puts tt
  end
end; nil
```

The full reindex timed at < 12 hours on staging with both machines (3 workers each). We should run it again with a single machine and double the workers.

**Comment by hackartisan** [comment]
To double the workers on one box:

1. ssh to one box and `sudo service sidekiq-workers stop`
2. ssh to the other box and `sudo vim /etc/systemd/system/sidekiq-workers.service`
3. in the bundle exec sidekiq change the `-c` arg to double its value (from 3 to 6)
4. run `sudo systemctl daemon-reload`
5. `sudo service sidekiq-workers restart`
6. observe the change in the sidekiq admin panel

**Comment by hackartisan** [comment]
The migrated index is finished running and the collections counts match.
