### ISSUE TITLE
Upgrade to Spotlight 3

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#839]
Upgrade to Spotlight 3, which uses Blacklight 7.

- As part of this upgrade we'll be able to (and maybe have to) remove the lines added in https://github.com/pulibrary/pomegranate/pull/838
- We ignored this one deprecation: https://github.com/pulibrary/pomegranate/issues/837

Step 1: Read any documented release notes to see if something is likely to break.
Step 2: Create tickets for any deprecations that exist from a clean test run.
Step 3: Try just upgrading the gem, see how hard this is going to be. Create follow-on tickets if we're going to be able to parallelize this work.

Related to https://github.com/pulibrary/dpul/issues/872

reference: 

* https://github.com/projectblacklight/spotlight/releases/tag/v3.0.0
* https://github.com/projectblacklight/blacklight/releases/tag/v7.0.0

**Comment by hackartisan** [comment]
we're upgrading from
- spotlight 2.9.0
- blacklight 6.24.0

**Comment by tpendragon** [comment]
Do this in a long-running branch.
