### ISSUE TITLE
RTL display issue - the table in browselists displays the rtl languages in the wrong place.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#854]
Also see [orangelight ticket #1824](https://github.com/pulibrary/orangelight/issues/1824). This is a display problem for the MARC records describing the incipit and explicit for the badakhshan items:
DPUL example: https://dpul.princeton.edu/badakhshan_collection/catalog/1v53k348k
Orangelight: https://catalog.princeton.edu/catalog/11404730
Figgy: https://figgy.princeton.edu/catalog/8c195e04-d7cf-4f7b-a1eb-06a68a49d217

the incipit: and explicit: should be on the left. example:
incipit: ان الله اصطفی آدم و نوحا و آل ابراهیم و آل عمران علی العالمین ذریتهم بعضها من بعض. قال النبی علیه السلام الصالحون لله و الطالعون
explicit: مهرافزون ابن یوسف علی شاه زن سید نادر خان

**Comment by tpendragon** [comment]
This is different than https://github.com/pulibrary/orangelight/issues/1824.

The problem here seems to be that the 500 note is just a 500a with an inline header. We have no way to tell where the english ends, and can't really say that it's standard practice that there's going to be "English: RTL" as a standard practice. Is that true?

**Comment by hackartisan** [comment]
@kelea99 What do you think of the question above?

**Comment by kelea99** [comment]
@hackartisan the short answer is yes, that is true that "English LTR: RTL" is not standard practice. However, I feel like we need to research ways and discuss with cataloging how we might able to display this information more clearly.

**Comment by hackartisan** [comment]
This ticket isn't really actionable. If catalogers do have a standardized way to treat this in metadata we could revisit.
