### ISSUE TITLE
Unpublished "Latin American ephemera: temporary" exhibit cannot be deleted from DPUL

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#865]
@escowles and and I have tried to delete and it throws a 405

Issues:
1. the https://dpul.princeton.edu/lae URL is also being used for Latin American Ephemera Ephemera project in figgy.  this cannot be changed, as the LAE blacklight site is dependent on it (see [here](https://github.com/pulibrary/lae-blacklight/blob/master/config/config.yml#L16-L19). 
2. @kelea99 has looked everywhere in figgy for the other collection duplicating the "https://dpul.princeton.edu/lae" URL that is feeding the unpublished DPUL site and can find nothing. It is only 5k items, so definitely not pulling from the entirety of the LAE project.   
3. we have had problems deleting unpublished collections in the past, which @hackartisan has been able to solve. not sure if this is the same issue or a new one.  See [ticket](https://github.com/pulibrary/pomegranate/issues/730)

Next Steps:

1. Create a chilean photographs collection with the chilean photographs project slug.
2. Add the chilean photographs collection to all the items in the chilean photograyphs project.
3. Move the folders from the chilean photographs ephemera project to the latin american ephemera project.
4. Delete the chilean photographs ephemera project.
5. Rename the LAE collection and change its slug to...something else.

The result of this:

1. Chilean photographs should sync to the LAE site.
2. The chilean photograph DPUL collection should continue to work.
3. The items in the LAE collection (not project) will not show up in the LAE site (but we didn't really expect them to before either)

**Comment by hackartisan** [comment]
As far as the deletion goes, yes this looks like a duplicate of #730 

But when it comes to the duplicate use of `lae` this is a new thing that needs to be resolved. I'm going to re-write this issue to reflect that problem.

**Comment by kelea99** [comment]
Oops. I selected Latin American ephemera from. the DPUL pulldown to create a new collection, but only too late realized there were 2 "LAE" collection options. I chose...poorly. it's the same selection as the last time (approx 5k items). Id assume the second LAE collection is what I am wanting to try to create ( im trying to get the entire collection into DPUL) . Im so sorry, @hackartisan . can this be deleted again by someone? same 405 is happening.

**Comment by kelea99** [comment]
@hackartisan , I cannot chance the slug for LAE, as the DPUL slug is important (as I understand it)  for the LAE blacklight site (I know, it's weird).

**Comment by kelea99** [comment]
I have changed the DPUL URL for the figgy collection. there are no longer dpulicate URLs in figgy for LAE. the band formerly known as LAE figgy collection: https://figgy.princeton.edu/catalog/cbca8ecb-b92f-4ef0-8bdc-976ad9d10d91

The LAE ephemera project remains the same
