### ISSUE TITLE
Add date range rendering to show pages

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dpul#876]
Date range data is displaying the JSON payload in DPUL, examples here: 

https://dpul.princeton.edu/sae_sri_lanka_dissidents/catalog/38f53706-d9d3-4e6d-b9d5-038ec98762e3
https://dpul.princeton.edu/slavic/catalog/98169364-db38-47c2-bdfd-c9c4a754fbb4

We probably need something like the [range_string](https://github.com/pulibrary/figgy/blob/640417960fdeb93834ca9f0c9f5810b446605b17/app/resources/date_ranges/date_range_decorator.rb#L3) decorator method here, as it renders appropriately in Figgy ("approximately 1992-1993").

This is marked high priority as it affects the whole DPUL site.

**Comment by hackartisan** [comment]
I ran the reindex on this collection and this example is fixed: https://dpul.princeton.edu/sae_sri_lanka_dissidents/catalog/38f53706-d9d3-4e6d-b9d5-038ec98762e3

Running the other collection now. @kelynch do we want all the collections run or just certain ones?

**Comment by kelynch** [comment]
Let's run all the collections to ensure that the issue is addressed across the lot.

**Comment by hackartisan** [comment]
I checked the exhibits to see which ones are displaying this field and there are only 4 including the 2 mentioned here. I will just click the reindex button for the other 2.

```
> exhibits = Spotlight::Exhibit.all.to_a
> selected = exhibits.select { |e| (e.blacklight_config.show_fields.select { |a| a == "readonly_date-range_ssim" }).present? }
> selected.map { |e| [e.id, e.slug] }
=> [[71, "sae_sri_lanka_dissidents"], [70, "cuba-tourism"], [15, "slavic"], [46, "sae"]]
```

**Comment by hackartisan** [comment]
reindexing is done.
