### ISSUE TITLE
Can we make all DPUL exhibit texts (within the widgets on pages and in browse categories) searchable within a particular DPUL exhibit?

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#878]
speaking with an individual from Stanford, this feature/ability has been requested. However, early on, their devs indicated it would be rather hard/problematic/time consuming. What are your thoughts?

**Comment by hackartisan** [comment]
Yes, only records are indexed. None of the page content of the site is indexed. The results page lists digital object records. This would be a significant new feature, possibly involving the creation of a new index depending on how design discussions went.

**Comment by kelea99** [comment]
Good to know. Since it has been asked for by folks at another institution and DPUL is continuously seeing more use, I thought it would be good to ask, just in case.  Thanks!

**Comment by kelea99** [comment]
Closing this. answer noted and not a priority.
