### ISSUE TITLE
Eliminate case sensitivity in hyper-linked search functionality (Keywords, for example)

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#887]
linked keywords in DPUL are case sensitive with search. "Christianity" and "christianity" show up as separate search queries/results.  As a researcher, it is essential that I am able to discover everything within that keyword/search parameter, regardless of capitalization. 

Example collection with keywords (currently unpublished - sign in to view): https://dpul.princeton.edu/sae_sri_lanka_dissidents/browse/collection-of-tissa-balasuriya

**Comment by tpendragon** [comment]
This is probably because it's keywords_ssim vs keywords_tesim.

**Comment by hackartisan** [comment]
@tpendragon observed that keywords weren't included in the default search

**Comment by hackartisan** [comment]
The functionality here is provided by blacklight's `link_to_search`. I really think this is the intended behavior. It's actually being renamed `link_to_facet`. Facet values don't provide the kind of string processing that other types of fields do because it's expected that they be very precise. Generally a data cleanup would be used to resolve this type of problem. If keyword was selected as a facet value for this collection the faceted search results will also suffer from this same issue until the data is cleaned. @tpendragon do you have a different perspective?

**Comment by tpendragon** [comment]
It seems like the standard way to fix this is to present facets from a field without the lowercase, but facet via a field with lowercase. I'm not sure if Blacklight can display differently, and I don't think we're indexing into a field which lowercases but doesn't tokenize.

Options to fix:

1. Clean up the non-lowercased keys.
2. Do 1, but also make it so keyword lowercases on save.
3. Add a special field type in solr which lowercases but doesn't tokenize, and index keywords into there.

2 is probably easiest and most complete?

**Comment by hackartisan** [comment]
And then also capitalize them (sentence case) on presentation, I assume. Since most of them are capitalized.

This seems like a reasonable solution.

**Comment by hackartisan** [comment]
@kelea99 the keywords are now being forced to lowercase on import. I reindexed the collection in question. Could you let me know if this resolves the issue?

**Comment by kelea99** [comment]
Testing now.  tested capitalized terms in search bar and it works, but throws back different results. I would assume this is due to other case sensitive metadata bits we haven't addressed. What I will say is the standardization of the keywords by forcing all lowercase works, and works well. So the request for Keywords has been fulfilled. I have sent to Ellen to test and will confirm with her today as well, @hackartisan , and update here if we can close the ticket.

**Comment by kelea99** [comment]
Looks great, @hackartisan! Approved by Stakeholder, too. Closing ticket
