### ISSUE TITLE
American Jewess MVW is not displaying in DPUL or online Catalog

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#896]
the MVW is not coming up and only a black screen is visible for https://catalog.princeton.edu/catalog/9138143 and https://dpul.princeton.edu/wa/catalog/d217qt45s. Displaying fine in figgy

If I sign in, still a no go. cannot see anything.  I do not know if others are affected (and why).  Tested on Chrome, Firefox, and Safari. Reported by Steve Ferguson

**Comment by tpendragon** [comment]
This is because the first volume is marked private (https://figgy.princeton.edu/catalog/20c031a8-70fc-4d75-a30f-4438034f0e4f)

**Comment by kelea99** [comment]
Changed to open just now

**Comment by kelea99** [comment]
Works! Thank you!
