### ISSUE TITLE
UV issues: "Contents" column for a MVW is not showing in Chrome, but is displaying fine in Orangelight

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#900]
Assuming its going to mobile mode,  sounds similar to Pulfalight issue#787, @sdellis and @tpendragon . 

Reported by Steve F.  Contents column displays fine for Steve in orangelight, but does not in DPUL when using Chrome. However,  he tried Safari on his Mac and  the viewer displayed fine for both the catalog and dpul
 
Hardware he is using: MacBook Air (2019 model)  (Ill get screen size)
Browser: Chrome.  
 

DPUL in chrome: ![image](https://user-images.githubusercontent.com/45043014/117353036-a9550b00-ae7d-11eb-85d5-6150736abcb4.png)

online catalog in chrome: 
![image](https://user-images.githubusercontent.com/45043014/117353097-b5d96380-ae7d-11eb-9713-cd3eacfe64cc.png)

**Comment by hackartisan** [comment]
The item is in dpul here: https://dpul.princeton.edu/wa/catalog/d217qt45s

It looks okay to me. Need replication.

**Comment by kelea99** [comment]
Can't replicate. closing for now but will reopen if it is reported again.
