### ISSUE TITLE
As a researcher, I would like to initiate a search and have the volume highlighted in a MVW that I might be interested in.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#910]
This came up with G&B and Postcards, where one building might have a very long listing of volumes in a MVW (Firestone library, for example). If a researcher searches for a term and is directed to Firestone Library, they will need to go through every volume until they find what they are looking for.  Is there a way to highlight the volume(s) where the search term is found?

**Comment by hackartisan** [comment]
@kelea99 Can you give a specific example of the search text and the volume that should be identified? I'm trying to understand whether this is metadata on the volume or OCR text.

**Comment by kelea99** [comment]
@hackartisan I am iceboxing this ticket because of a conversation regarding these collections last week.  @escowles , Im closing the ticket until its decided what is happening with these collections. Please reopen, if you prefer.
