### ISSUE TITLE
As a site builder, I would like to be able to include side search refining facets for item level metadata included in the "more information" slide for each item.       

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#914]
A request for Grounds and Buildings and Postcards from stakeholders.  Both collections have more accurate item level descriptions that would  be more helpful with the faceting than that of the component level fields.  can we map these fields to DPUL from the db that it is pulling from?

**Comment by hackartisan** [comment]
@kelea99 why was the decision made to group these in multi-volume works?

**Comment by kelea99** [comment]
The decision was made to turn these items into MVW by ADAPT, who wanted to retain item level information provided by a researcher, but they did not want it added to the FA (hence making it necessary for items to be displayed in one viewer, but also with their item level information in some way). DPUL was also not chosen as an option, as folks wanted the item level information preserved in figgy.  @escowles , i feel this should be iceboxed like #910 , until decisions/confirmations are made for these collections. Closing, but please reopen if you prefer.

**Comment by escowles** [comment]
Yes, I think this is the same issue — we're using MVWs to try to have more granular items in some contexts, and a group of them in a viewer in another context. At the time, we talked about other options for handling this (e.g., displaying a viewer that contained all objects in a collection, or all objects linked to a finding aid component https://github.com/pulibrary/figgy/issues/3815). Given the performance and functionalities with the MVW approach, I think it's time to revisit that discussion.
