### ISSUE TITLE
As an Admin User, when I click on " feature pages" and "about pages" in the curation facet of my dashboard, an error is thrown up.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#916]
@hackartisan  this is rather urgent, as it is holding up a DPUL site that is being worked on by students in SC for a class.

impact: the DPUL site cannot be publlshed until another page is created by Brian (the graduate student overseeing the work for the DPUL site), thereby completing the site for the class. 

Error I/he is being given:
![Screen Shot 2021-05-24 at 2 35 25 PM](https://user-images.githubusercontent.com/45043014/119392670-0d5d3900-bc9e-11eb-9ee1-56c460718c1b.png)

**Comment by kelea99** [comment]
Collections affected: seemingly all of them

**Comment by hackartisan** [comment]
👀

**Comment by hackartisan** [comment]
It looks like this is a bug resulting from a rails security update: https://github.com/advisories/GHSA-hjg4-8q5f-x6fm / https://github.com/rails/rails/commit/c4c21a9f8d7c9c8ca6570bdb82d64e2dc860e62c

the error in honeybadger:
https://app.honeybadger.io/projects/51733/faults/79350481

**Comment by hackartisan** [comment]
@kelea99, thanks to @bess this is sorted out and it's deployed.

**Comment by kelea99** [comment]
@hackartisan and @bess , you both are awesome. thank you so much!!

**Comment by kelea99** [comment]
Works!
