### ISSUE TITLE
"The Page you requested does not exist" error is coming up more consistently for a user when opening page in incognito window

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#928]
I have tried in Firefox, Safari, and Chrome and cannot replicate this error.  Made ticket to document error, should it happend again. 

Collection affected: https://dpul.princeton.edu/redefining_old_nassau
Curator: April Armstrong

Original Correspondence below.  Confirmed that she is logged in when she gets the error (screenshot also provided).  and the error is not consistent,  but it happening more frequently for her. 

 I wondered if you can help me with a persistent error message I've been getting. Sometimes it helps to open the site in an "incognito" window, but even then I often get an error message, "The page you requested doesn't exist." It's an intermittent error, so I am sometimes able to get in, but not all the time, and the error is now coming a lot more frequently.

![image](https://user-images.githubusercontent.com/45043014/128394903-cae621cd-9c89-48cd-9233-e317837ba749.png)

**Comment by hackartisan** [comment]
@kelea99 is this still happening?

**Comment by kelea99** [comment]
I cannot reproduce the error. Wrote to stakeholder this morning to check in with them as well.

**Comment by hackartisan** [comment]
@kelea99 any response? Shall we close this?

**Comment by kelea99** [comment]
No response. Closing issue until we hear this is still an issue.
