### ISSUE TITLE
Batch tagging of items needed for a sub collection of  East Asian Library Supplementary Materials Exhibit

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#930]
There are 344 items in the East Asian Library Supplementary Materials Exhibit  dpul exhibition that are a sub collection of the Supplementary Materials ([Link here](https://dpul.princeton.edu/ealtoc/browse/chinese-archival-handbooks).  The sub collection of 344 items need the following DPUL exhibit tags (already created in DPUL exhibit):
1. Table of Contents
2. List of Fonds

Confirmed with @tventimi - This is not critical and can wait, if needed, until upgrade to 3.0 this year (user-initiated batch tagging is available in 3.0).  Creating ticket in case status of need changes

**Comment by tventimi** [comment]
I ended up adding the tags manually.  Thanks anyway.
