### ISSUE TITLE
Look into how theming works in Spotlight 3.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul#932]
Implementation: https://github.com/pulibrary/dpul/issues/872

It'd be good to know how the feature works even before we get Spotlight updated.

**Comment by sdellis** [comment]
Simple documentation of theming: 
1. Add thumbnail image named as `{theme-name}_preview.png` to themes directory for each theme. (example: `app/assets/images/spotlight/themes/default_preview.png`)
2. Create stylesheets for each theme with a naming convention of `application_{theme-name}.scss` (note: application.scss is the default theme)
3. Remove ` *= require_tree .` line from `application.scss`
4. Add `Rails.application.config.assets.precompile += %w( application_{theme-name}.css )` to `/config/initializers/assets.rb`
5. Add `Spotlight::Engine.config.exhibit_themes = %w[{theme-name} default]` to `/config/initializers/spotlight_initializer.rb`
