### ISSUE TITLE
pul_assets master to main

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/dpul#944]
I have renamed the master branch to main in pul_assets.  Dpul should update the Gemfile and Gefile.lock for this change.

**Comment by carolyncole** [comment]
Actually you are pinned to s specific reference, so it may not me needed

**Comment by hackartisan** [comment]
Thanks @carolyncole. We were talking about whether / how we might be able to move away from pul_assets, so we'll probably circle back to this once we finish the spotlight upgrade we're undertaking now.

**Comment by tpendragon** [comment]
Will be done as part of #839.
