### ISSUE TITLE
Single Figgy resource in two collections has the same access_identifier / noid

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/dpul#947]
Is this a problem?

For reference:
https://dpul.princeton.edu/music/catalog/5e8cff75-3342-41b4-a1bc-3397a52f3448.json
https://dpul.princeton.edu/performances/catalog/5e8cff75-3342-41b4-a1bc-3397a52f3448.json

**Comment by eliotjordan** [comment]
I'm guessing not. The noid is the FiggyID. Each resource has a different exhibit and solr document.

**Comment by tpendragon** [comment]
Yeah this is fine. Our implementation has one resource per figgy resource per collection it's in.
