### ISSUE TITLE
Add link_to_facet in BlacklightConfiguration index_fields that have link_to_search

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul#965]
We may or may not have to do this. see if links break on show pages!

Go through all the `Spotlight::BlacklightConfiguration` objects and add `link_to_facet` to anything in `index_fields` that has `link_to_search`

example of finding the index fields to add this to:
`blacklight_configuration.index_fields.reject { |k, v| v["link_to_search"].nil? }.keys`

There are also references in our code to `link_to search` and we should probably change those.

background: 
* we had to change the tests to make the show presenter work: 
* https://github.com/projectblacklight/blacklight/commit/ab3dbf954688c339e82d266634472ce3d0c426e2

**Comment by eliotjordan** [comment]
Can confirm that the links are not appearing where they should.

https://dpul.princeton.edu/sae_sri_lanka_dissidents/catalog/90d076f7-b514-4276-8b55-51224db26a2a
vs.
https://dpul-staging.princeton.edu/sae_sri_lanka_dissidents/catalog/90d076f7-b514-4276-8b55-51224db26a2a

**Comment by eliotjordan** [comment]
Will need to migrate.
