### ISSUE TITLE
Wipe DPUL-Staging, mirror the state of production, make that a repeatable process.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul#979]
We'll need to test this upgrade against production data several times. We have production backups of solr and a way to restore them (https://github.com/pulibrary/pul_solr#solrcloud-backups) as well as production backups of the postgres database on Google cloud -- link to these is on slack pinned in the #figgy channel.

Ideally we should have a repeatable process to do this in relatively short order, so we can try deploying to a production-like stack multiple times.

* cap task? <-- this will make it easiest for us to invoke
* ansible playbook?
   * related work: https://github.com/pulibrary/princeton_ansible/blob/e3ef2da46d1d5877143270fba88bf4e9a2d3c382/playbooks/postgresql_db_migration.yml - although note this can't restore it to a db with a different name -- it's designed to move between 2 different db machines.

VMs involved:

- 3 solr-staging VMs (a cloud)
- 3 solr-prod VMs (a cloud)
- 1 postgres staging VM
- 1 postgres prod VM

First:
1. find the solr backup.  note date as YYYYMMDD.

postgres:
1. We need to add an additional dump to the automated backup that outputs using the `-Fc` flag.
1. download backup from [date] from google cloud
   1. requires: google cloud credentials
      4. Create a key that has access to these files? save this in lastpass or ansible vault and access it from there. Give it very limited permissions.
      5. Does this imply automating the creation of that role? We've done this in the past just by documenting the command.
   1. Is there a local copy?
      2. There is a local copy but dpul doesn't have the right mount.
2. there's a postgres command to restore database from backup (pg_restore)
   3. question: is the database name already hard-coded in the dump?
      3. if yes, restore it and then rename it? -- can't do this because prod and staging are on the same postgres.
      4. use pg_restore and specify the staging db. use `--no-owner` flag to avoid assigning the wrong owner to all the tables. use `--clean` flag to empty the staging db as a first step.

Google way:
2. write a rake task and use the google cloud library in ruby
3. in ansible, put this google cloud storage key

Solr:
1. Delete the collection
   2. `curl 'http://lib-solr-staging.princeton.edu:8983/solr/admin/collections?action=DELETE&name=dpul-staging'`
2. run the solr restore command, give it the path to the production backup
  3. `$ curl "http://lib-solr-staging.princeton.edu:8983/solr/admin/collections?action=RESTORE&name=dpul-production-[date].bk&collection=dpul-staging&location=/mnt/solr_backup/solr7/production/[date]"` -- this takes a couple minutes.
4. We can run this from the dpul box.

**Comment by hackartisan** [comment]
Still need:
- A cap task
- documentation that we need to pull it off the load balancer or shut down nginx
   - or allow deploy user to shut down nginx and write it into the cap task
- document that you can't run it for any date past 9/23 until #1023 is resolved.

**Comment by kayiwa** [comment]
can we iterate over this
```
if [ $ENABLE_CUSTOM_BACKUPS = "yes" ]
		then
			echo "Custom backup of $DATABASE"
	
			if ! pg_dump -Fc -h "$HOSTNAME" -U "$USERNAME" "$DATABASE" -f $FINAL_BACKUP_DIR"$DATABASE".custom.in_progress; then
				echo "[!!ERROR!!] Failed to produce custom backup database $DATABASE"
			else
				mv $FINAL_BACKUP_DIR"$DATABASE".custom.in_progress $FINAL_BACKUP_DIR"$DATABASE".custom
			fi
		fi
```

**Comment by hackartisan** [comment]
Added cap task, documented, and ran it a few more times. seems to work well.
